namespace AppBase
{
    partial class frmBuscarDerivarProveedor_413BE
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tlpPrincipal = new System.Windows.Forms.TableLayoutPanel();
            this.grpReclamos = new System.Windows.Forms.GroupBox();
            this.dgvReclamos = new System.Windows.Forms.DataGridView();
            this.dgvReclamosColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColFechaAlta = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColConsorcio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColCategoria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColPrioridad = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColTipoImputacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.grpProveedores = new System.Windows.Forms.GroupBox();
            this.dgvProveedores = new System.Windows.Forms.DataGridView();
            this.dgvProveedoresColProveedor = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvProveedoresColPrecioPromedio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvProveedoresColTiempoPromedio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvProveedoresColTasaReincidencia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.tabCriterios = new System.Windows.Forms.TabControl();
            this.tpMejorPrecio = new System.Windows.Forms.TabPage();
            this.tpRecomendado = new System.Windows.Forms.TabPage();
            this.tpMasRapido = new System.Windows.Forms.TabPage();
            this.tpMasEficiente = new System.Windows.Forms.TabPage();
            this.grpDerivacion = new System.Windows.Forms.GroupBox();
            this.lblSla = new System.Windows.Forms.Label();
            this.numSla = new System.Windows.Forms.NumericUpDown();
            this.btnDerivar = new System.Windows.Forms.Button();
            this.lbReclamoDerivado = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgvReclamos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvProveedores)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSla)).BeginInit();
            this.tlpPrincipal.SuspendLayout();
            this.grpReclamos.SuspendLayout();
            this.grpProveedores.SuspendLayout();
            this.tabCriterios.SuspendLayout();
            this.tpMejorPrecio.SuspendLayout();
            this.tpRecomendado.SuspendLayout();
            this.tpMasRapido.SuspendLayout();
            this.tpMasEficiente.SuspendLayout();
            this.grpDerivacion.SuspendLayout();
            this.SuspendLayout();
            this.tlpPrincipal.Controls.Add(this.grpReclamos, 0, 0);
            this.tlpPrincipal.Controls.Add(this.grpProveedores, 0, 1);
            this.tlpPrincipal.Controls.Add(this.grpDerivacion, 0, 2);
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 40F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 60F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 90F));
            this.tlpPrincipal.ColumnCount = 1;
            this.tlpPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpPrincipal.RowCount = 3;
            this.tlpPrincipal.Padding = new System.Windows.Forms.Padding(9);
            this.tlpPrincipal.Name = "tlpPrincipal";
            this.tlpPrincipal.TabIndex = 0;
            this.grpReclamos.Controls.Add(this.dgvReclamos);
            this.grpReclamos.Size = new System.Drawing.Size(1076, 240);
            this.grpReclamos.TabStop = false;
            this.grpReclamos.Text = "Reclamos clasificados";
            this.grpReclamos.Tag = "grp_bus_grpReclamos";
            this.grpReclamos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpReclamos.Name = "grpReclamos";
            this.grpReclamos.TabIndex = 0;
            this.dgvReclamos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvReclamosColId, this.dgvReclamosColFechaAlta, this.dgvReclamosColConsorcio, this.dgvReclamosColCategoria, this.dgvReclamosColPrioridad, this.dgvReclamosColTipoImputacion});
            this.dgvReclamos.AllowUserToAddRows = false;
            this.dgvReclamos.AllowUserToDeleteRows = false;
            this.dgvReclamos.AllowUserToResizeRows = false;
            this.dgvReclamos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvReclamos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvReclamos.MultiSelect = false;
            this.dgvReclamos.ReadOnly = true;
            this.dgvReclamos.RowHeadersVisible = false;
            this.dgvReclamos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvReclamos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvReclamos.Size = new System.Drawing.Size(1064, 210);
            this.dgvReclamos.Name = "dgvReclamos";
            this.dgvReclamos.TabIndex = 0;
            this.dgvReclamos.SelectionChanged += new System.EventHandler(this.dgvReclamos_SelectionChanged_413BE);
            this.dgvReclamosColId.HeaderText = "Id";
            this.dgvReclamosColId.Tag = "col_bus_dgvReclamosColId";
            this.dgvReclamosColId.Name = "dgvReclamosColId";
            this.dgvReclamosColId.ReadOnly = true;
            this.dgvReclamosColId.FillWeight = 30F;
            this.dgvReclamosColFechaAlta.HeaderText = "Fecha de alta";
            this.dgvReclamosColFechaAlta.Tag = "col_bus_dgvReclamosColFechaAlta";
            this.dgvReclamosColFechaAlta.Name = "dgvReclamosColFechaAlta";
            this.dgvReclamosColFechaAlta.ReadOnly = true;
            this.dgvReclamosColFechaAlta.FillWeight = 60F;
            this.dgvReclamosColConsorcio.HeaderText = "Consorcio";
            this.dgvReclamosColConsorcio.Tag = "col_bus_dgvReclamosColConsorcio";
            this.dgvReclamosColConsorcio.Name = "dgvReclamosColConsorcio";
            this.dgvReclamosColConsorcio.ReadOnly = true;
            this.dgvReclamosColConsorcio.FillWeight = 100F;
            this.dgvReclamosColCategoria.HeaderText = "Categoría";
            this.dgvReclamosColCategoria.Tag = "col_bus_dgvReclamosColCategoria";
            this.dgvReclamosColCategoria.Name = "dgvReclamosColCategoria";
            this.dgvReclamosColCategoria.ReadOnly = true;
            this.dgvReclamosColCategoria.FillWeight = 70F;
            this.dgvReclamosColPrioridad.HeaderText = "Prioridad";
            this.dgvReclamosColPrioridad.Tag = "col_bus_dgvReclamosColPrioridad";
            this.dgvReclamosColPrioridad.Name = "dgvReclamosColPrioridad";
            this.dgvReclamosColPrioridad.ReadOnly = true;
            this.dgvReclamosColPrioridad.FillWeight = 60F;
            this.dgvReclamosColTipoImputacion.HeaderText = "Tipo de imputación";
            this.dgvReclamosColTipoImputacion.Tag = "col_bus_dgvReclamosColTipoImputacion";
            this.dgvReclamosColTipoImputacion.Name = "dgvReclamosColTipoImputacion";
            this.dgvReclamosColTipoImputacion.ReadOnly = true;
            this.dgvReclamosColTipoImputacion.FillWeight = 70F;
            this.grpProveedores.Controls.Add(this.dgvProveedores);
            this.grpProveedores.Controls.Add(this.tabCriterios);
            this.grpProveedores.Size = new System.Drawing.Size(1076, 330);
            this.grpProveedores.TabStop = false;
            this.grpProveedores.Text = "Proveedores habilitados";
            this.grpProveedores.Tag = "grp_bus_grpProveedores";
            this.grpProveedores.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpProveedores.Name = "grpProveedores";
            this.grpProveedores.TabIndex = 1;
            this.dgvProveedores.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvProveedoresColProveedor, this.dgvProveedoresColPrecioPromedio, this.dgvProveedoresColTiempoPromedio, this.dgvProveedoresColTasaReincidencia});
            this.dgvProveedores.AllowUserToAddRows = false;
            this.dgvProveedores.AllowUserToDeleteRows = false;
            this.dgvProveedores.AllowUserToResizeRows = false;
            this.dgvProveedores.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvProveedores.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvProveedores.MultiSelect = false;
            this.dgvProveedores.ReadOnly = true;
            this.dgvProveedores.RowHeadersVisible = false;
            this.dgvProveedores.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvProveedores.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvProveedores.Size = new System.Drawing.Size(1056, 268);
            this.dgvProveedores.Name = "dgvProveedores";
            this.dgvProveedores.TabIndex = 0;
            this.dgvProveedores.SelectionChanged += new System.EventHandler(this.dgvProveedores_SelectionChanged_413BE);
            this.dgvProveedoresColProveedor.HeaderText = "Proveedor";
            this.dgvProveedoresColProveedor.Tag = "col_bus_dgvProveedoresColProveedor";
            this.dgvProveedoresColProveedor.Name = "dgvProveedoresColProveedor";
            this.dgvProveedoresColProveedor.ReadOnly = true;
            this.dgvProveedoresColProveedor.FillWeight = 120F;
            this.dgvProveedoresColPrecioPromedio.HeaderText = "Precio promedio";
            this.dgvProveedoresColPrecioPromedio.Tag = "col_bus_dgvProveedoresColPrecioPromedio";
            this.dgvProveedoresColPrecioPromedio.Name = "dgvProveedoresColPrecioPromedio";
            this.dgvProveedoresColPrecioPromedio.ReadOnly = true;
            this.dgvProveedoresColPrecioPromedio.FillWeight = 60F;
            this.dgvProveedoresColTiempoPromedio.HeaderText = "Tiempo promedio (días)";
            this.dgvProveedoresColTiempoPromedio.Tag = "col_bus_dgvProveedoresColTiempoPromedio";
            this.dgvProveedoresColTiempoPromedio.Name = "dgvProveedoresColTiempoPromedio";
            this.dgvProveedoresColTiempoPromedio.ReadOnly = true;
            this.dgvProveedoresColTiempoPromedio.FillWeight = 60F;
            this.dgvProveedoresColTasaReincidencia.HeaderText = "Tasa de reincidencia (%)";
            this.dgvProveedoresColTasaReincidencia.Tag = "col_bus_dgvProveedoresColTasaReincidencia";
            this.dgvProveedoresColTasaReincidencia.Name = "dgvProveedoresColTasaReincidencia";
            this.dgvProveedoresColTasaReincidencia.ReadOnly = true;
            this.dgvProveedoresColTasaReincidencia.FillWeight = 60F;
            this.tabCriterios.Controls.Add(this.tpMejorPrecio);
            this.tabCriterios.Controls.Add(this.tpRecomendado);
            this.tabCriterios.Controls.Add(this.tpMasRapido);
            this.tabCriterios.Controls.Add(this.tpMasEficiente);
            this.tabCriterios.Dock = System.Windows.Forms.DockStyle.Top;
            this.tabCriterios.SelectedIndex = 0;
            this.tabCriterios.Size = new System.Drawing.Size(1056, 28);
            this.tabCriterios.Name = "tabCriterios";
            this.tabCriterios.TabIndex = 1;
            this.tabCriterios.SelectedIndexChanged += new System.EventHandler(this.tabCriterios_SelectedIndexChanged_413BE);
            this.tpMejorPrecio.Location = new System.Drawing.Point(4, 24);
            this.tpMejorPrecio.Padding = new System.Windows.Forms.Padding(3);
            this.tpMejorPrecio.Size = new System.Drawing.Size(1048, 0);
            this.tpMejorPrecio.Text = "Mejor precio";
            this.tpMejorPrecio.Tag = "tab_bus_tpMejorPrecio";
            this.tpMejorPrecio.UseVisualStyleBackColor = true;
            this.tpMejorPrecio.Name = "tpMejorPrecio";
            this.tpMejorPrecio.TabIndex = 0;
            this.tpRecomendado.Location = new System.Drawing.Point(4, 24);
            this.tpRecomendado.Padding = new System.Windows.Forms.Padding(3);
            this.tpRecomendado.Size = new System.Drawing.Size(1048, 0);
            this.tpRecomendado.Text = "Recomendado";
            this.tpRecomendado.Tag = "tab_bus_tpRecomendado";
            this.tpRecomendado.UseVisualStyleBackColor = true;
            this.tpRecomendado.Name = "tpRecomendado";
            this.tpRecomendado.TabIndex = 1;
            this.tpMasRapido.Location = new System.Drawing.Point(4, 24);
            this.tpMasRapido.Padding = new System.Windows.Forms.Padding(3);
            this.tpMasRapido.Size = new System.Drawing.Size(1048, 0);
            this.tpMasRapido.Text = "Más rápido";
            this.tpMasRapido.Tag = "tab_bus_tpMasRapido";
            this.tpMasRapido.UseVisualStyleBackColor = true;
            this.tpMasRapido.Name = "tpMasRapido";
            this.tpMasRapido.TabIndex = 2;
            this.tpMasEficiente.Location = new System.Drawing.Point(4, 24);
            this.tpMasEficiente.Padding = new System.Windows.Forms.Padding(3);
            this.tpMasEficiente.Size = new System.Drawing.Size(1048, 0);
            this.tpMasEficiente.Text = "Más eficiente";
            this.tpMasEficiente.Tag = "tab_bus_tpMasEficiente";
            this.tpMasEficiente.UseVisualStyleBackColor = true;
            this.tpMasEficiente.Name = "tpMasEficiente";
            this.tpMasEficiente.TabIndex = 3;
            this.grpDerivacion.Controls.Add(this.lblSla);
            this.grpDerivacion.Controls.Add(this.numSla);
            this.grpDerivacion.Controls.Add(this.btnDerivar);
            this.grpDerivacion.Size = new System.Drawing.Size(1076, 90);
            this.grpDerivacion.TabStop = false;
            this.grpDerivacion.Text = "Derivación";
            this.grpDerivacion.Tag = "grp_bus_grpDerivacion";
            this.grpDerivacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpDerivacion.Name = "grpDerivacion";
            this.grpDerivacion.TabIndex = 2;
            this.lblSla.AutoSize = true;
            this.lblSla.Location = new System.Drawing.Point(15, 40);
            this.lblSla.Text = "Plazo de resolución (SLA), en días";
            this.lblSla.Tag = "lb_bus_lblSla";
            this.lblSla.Name = "lblSla";
            this.lblSla.TabIndex = 0;
            this.numSla.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.numSla.Location = new System.Drawing.Point(250, 36);
            this.numSla.Maximum = new decimal(new int[] { 365, 0, 0, 0});
            this.numSla.Size = new System.Drawing.Size(80, 23);
            this.numSla.Value = new decimal(new int[] { 7, 0, 0, 0});
            this.numSla.Name = "numSla";
            this.numSla.TabIndex = 1;
            this.btnDerivar.Location = new System.Drawing.Point(360, 34);
            this.btnDerivar.Size = new System.Drawing.Size(120, 28);
            this.btnDerivar.Text = "Derivar";
            this.btnDerivar.Tag = "btn_bus_btnDerivar";
            this.btnDerivar.UseVisualStyleBackColor = true;
            this.btnDerivar.Enabled = false;
            this.btnDerivar.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnDerivar.Name = "btnDerivar";
            this.btnDerivar.TabIndex = 2;
            this.btnDerivar.Click += new System.EventHandler(this.btnDerivar_Click_413BE);
            this.lbReclamoDerivado.AutoSize = true;
            this.lbReclamoDerivado.Location = new System.Drawing.Point(3, 3);
            this.lbReclamoDerivado.Name = "lbReclamoDerivado";
            this.lbReclamoDerivado.Size = new System.Drawing.Size(120, 15);
            this.lbReclamoDerivado.TabIndex = 100;
            this.lbReclamoDerivado.Tag = "lb_bus_reclamoDerivado";
            this.lbReclamoDerivado.Text = "Reclamo derivado";
            this.lbReclamoDerivado.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.tlpPrincipal);
            this.Controls.Add(this.lbReclamoDerivado);
            this.MinimumSize = new System.Drawing.Size(900, 600);
            this.Name = "frmBuscarDerivarProveedor_413BE";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Buscar y derivar proveedor";
            this.Load += new System.EventHandler(this.frmBuscarDerivarProveedor_Load_413BE);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmBuscarDerivarProveedor_FormClosing_413BE);
            ((System.ComponentModel.ISupportInitialize)(this.dgvReclamos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvProveedores)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numSla)).EndInit();
            this.tlpPrincipal.ResumeLayout(false);
            this.grpReclamos.ResumeLayout(false);
            this.grpReclamos.PerformLayout();
            this.grpProveedores.ResumeLayout(false);
            this.grpProveedores.PerformLayout();
            this.tabCriterios.ResumeLayout(false);
            this.tpMejorPrecio.ResumeLayout(false);
            this.tpRecomendado.ResumeLayout(false);
            this.tpMasRapido.ResumeLayout(false);
            this.tpMasEficiente.ResumeLayout(false);
            this.grpDerivacion.ResumeLayout(false);
            this.grpDerivacion.PerformLayout();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpPrincipal;
        private System.Windows.Forms.GroupBox grpReclamos;
        private System.Windows.Forms.DataGridView dgvReclamos;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColFechaAlta;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColConsorcio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColCategoria;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColPrioridad;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColTipoImputacion;
        private System.Windows.Forms.GroupBox grpProveedores;
        private System.Windows.Forms.DataGridView dgvProveedores;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvProveedoresColProveedor;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvProveedoresColPrecioPromedio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvProveedoresColTiempoPromedio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvProveedoresColTasaReincidencia;
        private System.Windows.Forms.TabControl tabCriterios;
        private System.Windows.Forms.TabPage tpMejorPrecio;
        private System.Windows.Forms.TabPage tpRecomendado;
        private System.Windows.Forms.TabPage tpMasRapido;
        private System.Windows.Forms.TabPage tpMasEficiente;
        private System.Windows.Forms.GroupBox grpDerivacion;
        private System.Windows.Forms.Label lblSla;
        private System.Windows.Forms.NumericUpDown numSla;
        private System.Windows.Forms.Button btnDerivar;
        private System.Windows.Forms.Label lbReclamoDerivado;
    }
}
