namespace AppBase
{
    partial class frmCerrarReclamo_413BE
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tlpPrincipal = new System.Windows.Forms.TableLayoutPanel();
            this.grpDerivados = new System.Windows.Forms.GroupBox();
            this.dgvDerivados = new System.Windows.Forms.DataGridView();
            this.dgvDerivadosColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDerivadosColFechaAlta = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDerivadosColConsorcio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDerivadosColCategoria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDerivadosColPrioridad = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDerivadosColTipoImputacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.grpCierre = new System.Windows.Forms.GroupBox();
            this.lblDatosReclamo = new System.Windows.Forms.Label();
            this.txtDatosReclamo = new System.Windows.Forms.TextBox();
            this.lblInforme = new System.Windows.Forms.Label();
            this.txtInforme = new System.Windows.Forms.TextBox();
            this.lblNumeroFactura = new System.Windows.Forms.Label();
            this.txtNumeroFactura = new System.Windows.Forms.TextBox();
            this.lblCosto = new System.Windows.Forms.Label();
            this.numCosto = new System.Windows.Forms.NumericUpDown();
            this.btnCerrarReclamo = new System.Windows.Forms.Button();
            this.grpImputacion = new System.Windows.Forms.GroupBox();
            this.lblCuentaTitulo = new System.Windows.Forms.Label();
            this.lblCuenta = new System.Windows.Forms.Label();
            this.lblMontoTitulo = new System.Windows.Forms.Label();
            this.lblMonto = new System.Windows.Forms.Label();
            this.btnConfirmarCierre = new System.Windows.Forms.Button();
            this.btnCancelar = new System.Windows.Forms.Button();
            this.lbReclamoCerrado = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDerivados)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCosto)).BeginInit();
            this.tlpPrincipal.SuspendLayout();
            this.grpDerivados.SuspendLayout();
            this.grpCierre.SuspendLayout();
            this.grpImputacion.SuspendLayout();
            this.SuspendLayout();
            this.tlpPrincipal.Controls.Add(this.grpDerivados, 0, 0);
            this.tlpPrincipal.SetColumnSpan(this.grpDerivados, 2);
            this.tlpPrincipal.Controls.Add(this.grpCierre, 0, 1);
            this.tlpPrincipal.Controls.Add(this.grpImputacion, 1, 1);
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.tlpPrincipal.ColumnCount = 2;
            this.tlpPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpPrincipal.RowCount = 2;
            this.tlpPrincipal.Padding = new System.Windows.Forms.Padding(9);
            this.tlpPrincipal.Name = "tlpPrincipal";
            this.tlpPrincipal.TabIndex = 0;
            this.grpDerivados.Controls.Add(this.dgvDerivados);
            this.grpDerivados.Size = new System.Drawing.Size(1076, 220);
            this.grpDerivados.TabStop = false;
            this.grpDerivados.Text = "Reclamos derivados";
            this.grpDerivados.Tag = "grp_cie_grpDerivados";
            this.grpDerivados.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpDerivados.Name = "grpDerivados";
            this.grpDerivados.TabIndex = 0;
            this.dgvDerivados.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvDerivadosColId, this.dgvDerivadosColFechaAlta, this.dgvDerivadosColConsorcio, this.dgvDerivadosColCategoria, this.dgvDerivadosColPrioridad, this.dgvDerivadosColTipoImputacion});
            this.dgvDerivados.AllowUserToAddRows = false;
            this.dgvDerivados.AllowUserToDeleteRows = false;
            this.dgvDerivados.AllowUserToResizeRows = false;
            this.dgvDerivados.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDerivados.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDerivados.MultiSelect = false;
            this.dgvDerivados.ReadOnly = true;
            this.dgvDerivados.RowHeadersVisible = false;
            this.dgvDerivados.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDerivados.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDerivados.Size = new System.Drawing.Size(1064, 190);
            this.dgvDerivados.Name = "dgvDerivados";
            this.dgvDerivados.TabIndex = 0;
            this.dgvDerivados.SelectionChanged += new System.EventHandler(this.dgvDerivados_SelectionChanged_413BE);
            this.dgvDerivadosColId.HeaderText = "Id";
            this.dgvDerivadosColId.Tag = "col_cie_dgvDerivadosColId";
            this.dgvDerivadosColId.Name = "dgvDerivadosColId";
            this.dgvDerivadosColId.ReadOnly = true;
            this.dgvDerivadosColId.FillWeight = 30F;
            this.dgvDerivadosColFechaAlta.HeaderText = "Fecha de alta";
            this.dgvDerivadosColFechaAlta.Tag = "col_cie_dgvDerivadosColFechaAlta";
            this.dgvDerivadosColFechaAlta.Name = "dgvDerivadosColFechaAlta";
            this.dgvDerivadosColFechaAlta.ReadOnly = true;
            this.dgvDerivadosColFechaAlta.FillWeight = 60F;
            this.dgvDerivadosColConsorcio.HeaderText = "Consorcio";
            this.dgvDerivadosColConsorcio.Tag = "col_cie_dgvDerivadosColConsorcio";
            this.dgvDerivadosColConsorcio.Name = "dgvDerivadosColConsorcio";
            this.dgvDerivadosColConsorcio.ReadOnly = true;
            this.dgvDerivadosColConsorcio.FillWeight = 100F;
            this.dgvDerivadosColCategoria.HeaderText = "Categoría";
            this.dgvDerivadosColCategoria.Tag = "col_cie_dgvDerivadosColCategoria";
            this.dgvDerivadosColCategoria.Name = "dgvDerivadosColCategoria";
            this.dgvDerivadosColCategoria.ReadOnly = true;
            this.dgvDerivadosColCategoria.FillWeight = 70F;
            this.dgvDerivadosColPrioridad.HeaderText = "Prioridad";
            this.dgvDerivadosColPrioridad.Tag = "col_cie_dgvDerivadosColPrioridad";
            this.dgvDerivadosColPrioridad.Name = "dgvDerivadosColPrioridad";
            this.dgvDerivadosColPrioridad.ReadOnly = true;
            this.dgvDerivadosColPrioridad.FillWeight = 60F;
            this.dgvDerivadosColTipoImputacion.HeaderText = "Tipo de imputación";
            this.dgvDerivadosColTipoImputacion.Tag = "col_cie_dgvDerivadosColTipoImputacion";
            this.dgvDerivadosColTipoImputacion.Name = "dgvDerivadosColTipoImputacion";
            this.dgvDerivadosColTipoImputacion.ReadOnly = true;
            this.dgvDerivadosColTipoImputacion.FillWeight = 70F;
            this.grpCierre.Controls.Add(this.lblDatosReclamo);
            this.grpCierre.Controls.Add(this.txtDatosReclamo);
            this.grpCierre.Controls.Add(this.lblInforme);
            this.grpCierre.Controls.Add(this.txtInforme);
            this.grpCierre.Controls.Add(this.lblNumeroFactura);
            this.grpCierre.Controls.Add(this.txtNumeroFactura);
            this.grpCierre.Controls.Add(this.lblCosto);
            this.grpCierre.Controls.Add(this.numCosto);
            this.grpCierre.Controls.Add(this.btnCerrarReclamo);
            this.grpCierre.Size = new System.Drawing.Size(700, 448);
            this.grpCierre.TabStop = false;
            this.grpCierre.Text = "Cierre del reclamo";
            this.grpCierre.Tag = "grp_cie_grpCierre";
            this.grpCierre.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpCierre.Name = "grpCierre";
            this.grpCierre.TabIndex = 1;
            this.lblDatosReclamo.AutoSize = true;
            this.lblDatosReclamo.Location = new System.Drawing.Point(15, 28);
            this.lblDatosReclamo.Text = "Datos del reclamo";
            this.lblDatosReclamo.Tag = "lb_cie_lblDatosReclamo";
            this.lblDatosReclamo.Name = "lblDatosReclamo";
            this.lblDatosReclamo.TabIndex = 0;
            this.txtDatosReclamo.Location = new System.Drawing.Point(15, 48);
            this.txtDatosReclamo.Size = new System.Drawing.Size(670, 100);
            this.txtDatosReclamo.Multiline = true;
            this.txtDatosReclamo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDatosReclamo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtDatosReclamo.ReadOnly = true;
            this.txtDatosReclamo.Name = "txtDatosReclamo";
            this.txtDatosReclamo.TabIndex = 1;
            this.lblInforme.AutoSize = true;
            this.lblInforme.Location = new System.Drawing.Point(15, 162);
            this.lblInforme.Text = "Informe de resolución";
            this.lblInforme.Tag = "lb_cie_lblInforme";
            this.lblInforme.Name = "lblInforme";
            this.lblInforme.TabIndex = 2;
            this.txtInforme.Location = new System.Drawing.Point(15, 182);
            this.txtInforme.Size = new System.Drawing.Size(670, 80);
            this.txtInforme.Multiline = true;
            this.txtInforme.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtInforme.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtInforme.Name = "txtInforme";
            this.txtInforme.TabIndex = 3;
            this.lblNumeroFactura.AutoSize = true;
            this.lblNumeroFactura.Location = new System.Drawing.Point(15, 276);
            this.lblNumeroFactura.Text = "Número de factura (opcional)";
            this.lblNumeroFactura.Tag = "lb_cie_lblNumeroFactura";
            this.lblNumeroFactura.Name = "lblNumeroFactura";
            this.lblNumeroFactura.TabIndex = 4;
            this.txtNumeroFactura.Location = new System.Drawing.Point(15, 296);
            this.txtNumeroFactura.Size = new System.Drawing.Size(300, 23);
            this.txtNumeroFactura.Name = "txtNumeroFactura";
            this.txtNumeroFactura.TabIndex = 5;
            this.lblCosto.AutoSize = true;
            this.lblCosto.Location = new System.Drawing.Point(340, 276);
            this.lblCosto.Text = "Costo";
            this.lblCosto.Tag = "lb_cie_lblCosto";
            this.lblCosto.Name = "lblCosto";
            this.lblCosto.TabIndex = 6;
            this.numCosto.DecimalPlaces = 2;
            this.numCosto.Location = new System.Drawing.Point(340, 296);
            this.numCosto.Maximum = new decimal(new int[] { 999999999, 0, 0, 0});
            this.numCosto.Size = new System.Drawing.Size(200, 23);
            this.numCosto.ThousandsSeparator = true;
            this.numCosto.Name = "numCosto";
            this.numCosto.TabIndex = 7;
            this.btnCerrarReclamo.Location = new System.Drawing.Point(15, 344);
            this.btnCerrarReclamo.Size = new System.Drawing.Size(150, 30);
            this.btnCerrarReclamo.Text = "Cerrar reclamo";
            this.btnCerrarReclamo.Tag = "btn_cie_btnCerrarReclamo";
            this.btnCerrarReclamo.UseVisualStyleBackColor = true;
            this.btnCerrarReclamo.Enabled = false;
            this.btnCerrarReclamo.Name = "btnCerrarReclamo";
            this.btnCerrarReclamo.TabIndex = 8;
            this.btnCerrarReclamo.Click += new System.EventHandler(this.btnCerrarReclamo_Click_413BE);
            this.grpImputacion.Controls.Add(this.lblCuentaTitulo);
            this.grpImputacion.Controls.Add(this.lblCuenta);
            this.grpImputacion.Controls.Add(this.lblMontoTitulo);
            this.grpImputacion.Controls.Add(this.lblMonto);
            this.grpImputacion.Controls.Add(this.btnConfirmarCierre);
            this.grpImputacion.Controls.Add(this.btnCancelar);
            this.grpImputacion.Size = new System.Drawing.Size(364, 200);
            this.grpImputacion.TabStop = false;
            this.grpImputacion.Text = "Imputación resultante";
            this.grpImputacion.Tag = "grp_cie_grpImputacion";
            this.grpImputacion.Visible = false;
            this.grpImputacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpImputacion.Name = "grpImputacion";
            this.grpImputacion.TabIndex = 2;
            this.lblCuentaTitulo.AutoSize = true;
            this.lblCuentaTitulo.Location = new System.Drawing.Point(15, 40);
            this.lblCuentaTitulo.Text = "Cuenta imputada:";
            this.lblCuentaTitulo.Tag = "lb_cie_lblCuentaTitulo";
            this.lblCuentaTitulo.Name = "lblCuentaTitulo";
            this.lblCuentaTitulo.TabIndex = 0;
            this.lblCuenta.AutoSize = true;
            this.lblCuenta.Location = new System.Drawing.Point(140, 40);
            this.lblCuenta.Text = "";
            this.lblCuenta.Name = "lblCuenta";
            this.lblCuenta.TabIndex = 1;
            this.lblMontoTitulo.AutoSize = true;
            this.lblMontoTitulo.Location = new System.Drawing.Point(15, 75);
            this.lblMontoTitulo.Text = "Monto a imputar:";
            this.lblMontoTitulo.Tag = "lb_cie_lblMontoTitulo";
            this.lblMontoTitulo.Name = "lblMontoTitulo";
            this.lblMontoTitulo.TabIndex = 2;
            this.lblMonto.AutoSize = true;
            this.lblMonto.Location = new System.Drawing.Point(140, 75);
            this.lblMonto.Text = "";
            this.lblMonto.Name = "lblMonto";
            this.lblMonto.TabIndex = 3;
            this.btnConfirmarCierre.Location = new System.Drawing.Point(15, 130);
            this.btnConfirmarCierre.Size = new System.Drawing.Size(150, 30);
            this.btnConfirmarCierre.Text = "Confirmar cierre";
            this.btnConfirmarCierre.Tag = "btn_cie_btnConfirmarCierre";
            this.btnConfirmarCierre.UseVisualStyleBackColor = true;
            this.btnConfirmarCierre.Name = "btnConfirmarCierre";
            this.btnConfirmarCierre.TabIndex = 4;
            this.btnConfirmarCierre.Click += new System.EventHandler(this.btnConfirmarCierre_Click_413BE);
            this.btnCancelar.Location = new System.Drawing.Point(185, 130);
            this.btnCancelar.Size = new System.Drawing.Size(150, 30);
            this.btnCancelar.Text = "Cancelar";
            this.btnCancelar.Tag = "btn_cie_btnCancelar";
            this.btnCancelar.UseVisualStyleBackColor = true;
            this.btnCancelar.Name = "btnCancelar";
            this.btnCancelar.TabIndex = 5;
            this.btnCancelar.Click += new System.EventHandler(this.btnCancelar_Click_413BE);
            this.lbReclamoCerrado.AutoSize = true;
            this.lbReclamoCerrado.Location = new System.Drawing.Point(3, 3);
            this.lbReclamoCerrado.Name = "lbReclamoCerrado";
            this.lbReclamoCerrado.Size = new System.Drawing.Size(120, 15);
            this.lbReclamoCerrado.TabIndex = 100;
            this.lbReclamoCerrado.Tag = "lb_cie_reclamoCerrado";
            this.lbReclamoCerrado.Text = "Reclamo cerrado";
            this.lbReclamoCerrado.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.tlpPrincipal);
            this.Controls.Add(this.lbReclamoCerrado);
            this.MinimumSize = new System.Drawing.Size(1120, 740);
            this.Name = "frmCerrarReclamo_413BE";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Cerrar reclamo e imputar costo";
            this.Load += new System.EventHandler(this.frmCerrarReclamo_Load_413BE);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmCerrarReclamo_FormClosing_413BE);
            ((System.ComponentModel.ISupportInitialize)(this.dgvDerivados)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCosto)).EndInit();
            this.tlpPrincipal.ResumeLayout(false);
            this.grpDerivados.ResumeLayout(false);
            this.grpDerivados.PerformLayout();
            this.grpCierre.ResumeLayout(false);
            this.grpCierre.PerformLayout();
            this.grpImputacion.ResumeLayout(false);
            this.grpImputacion.PerformLayout();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpPrincipal;
        private System.Windows.Forms.GroupBox grpDerivados;
        private System.Windows.Forms.DataGridView dgvDerivados;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColFechaAlta;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColConsorcio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColCategoria;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColPrioridad;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDerivadosColTipoImputacion;
        private System.Windows.Forms.GroupBox grpCierre;
        private System.Windows.Forms.Label lblDatosReclamo;
        private System.Windows.Forms.TextBox txtDatosReclamo;
        private System.Windows.Forms.Label lblInforme;
        private System.Windows.Forms.TextBox txtInforme;
        private System.Windows.Forms.Label lblNumeroFactura;
        private System.Windows.Forms.TextBox txtNumeroFactura;
        private System.Windows.Forms.Label lblCosto;
        private System.Windows.Forms.NumericUpDown numCosto;
        private System.Windows.Forms.Button btnCerrarReclamo;
        private System.Windows.Forms.GroupBox grpImputacion;
        private System.Windows.Forms.Label lblCuentaTitulo;
        private System.Windows.Forms.Label lblCuenta;
        private System.Windows.Forms.Label lblMontoTitulo;
        private System.Windows.Forms.Label lblMonto;
        private System.Windows.Forms.Button btnConfirmarCierre;
        private System.Windows.Forms.Button btnCancelar;
        private System.Windows.Forms.Label lbReclamoCerrado;
    }
}
