namespace AppBase
{
    partial class frmCargarClasificarReclamo_413BE
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tlpPrincipal = new System.Windows.Forms.TableLayoutPanel();
            this.grpCarga = new System.Windows.Forms.GroupBox();
            this.lblConsorcio = new System.Windows.Forms.Label();
            this.cboConsorcio = new System.Windows.Forms.ComboBox();
            this.lblUbicacion = new System.Windows.Forms.Label();
            this.rdoUnidadFuncional = new System.Windows.Forms.RadioButton();
            this.rdoAreaComun = new System.Windows.Forms.RadioButton();
            this.cboUnidadFuncional = new System.Windows.Forms.ComboBox();
            this.cboAreaComun = new System.Windows.Forms.ComboBox();
            this.lblConsorcista = new System.Windows.Forms.Label();
            this.cboConsorcista = new System.Windows.Forms.ComboBox();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cboCategoria = new System.Windows.Forms.ComboBox();
            this.lblDescripcion = new System.Windows.Forms.Label();
            this.txtDescripcion = new System.Windows.Forms.TextBox();
            this.lblFotos = new System.Windows.Forms.Label();
            this.lstFotos = new System.Windows.Forms.ListBox();
            this.btnAdjuntarFoto = new System.Windows.Forms.Button();
            this.btnGuardar = new System.Windows.Forms.Button();
            this.dlgFoto = new System.Windows.Forms.OpenFileDialog();
            this.grpPendientes = new System.Windows.Forms.GroupBox();
            this.dgvPendientes = new System.Windows.Forms.DataGridView();
            this.dgvPendientesColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPendientesColFechaAlta = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPendientesColConsorcio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPendientesColUbicacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPendientesColCategoria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvPendientesColEstado = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.grpClasificacion = new System.Windows.Forms.GroupBox();
            this.lblDatosReclamo = new System.Windows.Forms.Label();
            this.txtDatosReclamo = new System.Windows.Forms.TextBox();
            this.lblCategoriaClasificacion = new System.Windows.Forms.Label();
            this.cboCategoriaClasificacion = new System.Windows.Forms.ComboBox();
            this.lblTipoImputacion = new System.Windows.Forms.Label();
            this.cboTipoImputacion = new System.Windows.Forms.ComboBox();
            this.lblPrioridad = new System.Windows.Forms.Label();
            this.cboPrioridad = new System.Windows.Forms.ComboBox();
            this.btnClasificar = new System.Windows.Forms.Button();
            this.lbReclamoRegistrado = new System.Windows.Forms.Label();
            this.lbConfirmarReincidencia = new System.Windows.Forms.Label();
            this.lbReclamoClasificado = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgvPendientes)).BeginInit();
            this.tlpPrincipal.SuspendLayout();
            this.grpCarga.SuspendLayout();
            this.grpPendientes.SuspendLayout();
            this.grpClasificacion.SuspendLayout();
            this.SuspendLayout();
            this.tlpPrincipal.Controls.Add(this.grpCarga, 0, 0);
            this.tlpPrincipal.Controls.Add(this.grpPendientes, 1, 0);
            this.tlpPrincipal.Controls.Add(this.grpClasificacion, 0, 1);
            this.tlpPrincipal.SetColumnSpan(this.grpClasificacion, 2);
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 50F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.tlpPrincipal.ColumnCount = 2;
            this.tlpPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpPrincipal.RowCount = 2;
            this.tlpPrincipal.Padding = new System.Windows.Forms.Padding(9);
            this.tlpPrincipal.Name = "tlpPrincipal";
            this.tlpPrincipal.TabIndex = 0;
            this.grpCarga.Controls.Add(this.lblConsorcio);
            this.grpCarga.Controls.Add(this.cboConsorcio);
            this.grpCarga.Controls.Add(this.lblUbicacion);
            this.grpCarga.Controls.Add(this.rdoUnidadFuncional);
            this.grpCarga.Controls.Add(this.rdoAreaComun);
            this.grpCarga.Controls.Add(this.cboUnidadFuncional);
            this.grpCarga.Controls.Add(this.cboAreaComun);
            this.grpCarga.Controls.Add(this.lblConsorcista);
            this.grpCarga.Controls.Add(this.cboConsorcista);
            this.grpCarga.Controls.Add(this.lblCategoria);
            this.grpCarga.Controls.Add(this.cboCategoria);
            this.grpCarga.Controls.Add(this.lblDescripcion);
            this.grpCarga.Controls.Add(this.txtDescripcion);
            this.grpCarga.Controls.Add(this.lblFotos);
            this.grpCarga.Controls.Add(this.lstFotos);
            this.grpCarga.Controls.Add(this.btnAdjuntarFoto);
            this.grpCarga.Controls.Add(this.btnGuardar);
            this.grpCarga.Size = new System.Drawing.Size(530, 350);
            this.grpCarga.TabStop = false;
            this.grpCarga.Text = "Cargar reclamo";
            this.grpCarga.Tag = "grp_car_grpCarga";
            this.grpCarga.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpCarga.Name = "grpCarga";
            this.grpCarga.TabIndex = 0;
            this.lblConsorcio.AutoSize = true;
            this.lblConsorcio.Location = new System.Drawing.Point(15, 32);
            this.lblConsorcio.Text = "Consorcio";
            this.lblConsorcio.Tag = "lb_car_lblConsorcio";
            this.lblConsorcio.Name = "lblConsorcio";
            this.lblConsorcio.TabIndex = 0;
            this.cboConsorcio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConsorcio.FormattingEnabled = true;
            this.cboConsorcio.Location = new System.Drawing.Point(120, 28);
            this.cboConsorcio.Size = new System.Drawing.Size(390, 23);
            this.cboConsorcio.Name = "cboConsorcio";
            this.cboConsorcio.TabIndex = 1;
            this.cboConsorcio.SelectedIndexChanged += new System.EventHandler(this.cboConsorcio_SelectedIndexChanged_413BE);
            this.lblUbicacion.AutoSize = true;
            this.lblUbicacion.Location = new System.Drawing.Point(15, 66);
            this.lblUbicacion.Text = "Ubicación";
            this.lblUbicacion.Tag = "lb_car_lblUbicacion";
            this.lblUbicacion.Name = "lblUbicacion";
            this.lblUbicacion.TabIndex = 2;
            this.rdoUnidadFuncional.AutoSize = true;
            this.rdoUnidadFuncional.Checked = true;
            this.rdoUnidadFuncional.Location = new System.Drawing.Point(120, 64);
            this.rdoUnidadFuncional.Size = new System.Drawing.Size(115, 19);
            this.rdoUnidadFuncional.TabStop = true;
            this.rdoUnidadFuncional.Text = "Unidad funcional";
            this.rdoUnidadFuncional.Tag = "rdo_car_rdoUnidadFuncional";
            this.rdoUnidadFuncional.UseVisualStyleBackColor = true;
            this.rdoUnidadFuncional.Name = "rdoUnidadFuncional";
            this.rdoUnidadFuncional.TabIndex = 3;
            this.rdoUnidadFuncional.CheckedChanged += new System.EventHandler(this.rdoUnidadFuncional_CheckedChanged_413BE);
            this.rdoAreaComun.AutoSize = true;
            this.rdoAreaComun.Location = new System.Drawing.Point(270, 64);
            this.rdoAreaComun.Size = new System.Drawing.Size(88, 19);
            this.rdoAreaComun.Text = "Área común";
            this.rdoAreaComun.Tag = "rdo_car_rdoAreaComun";
            this.rdoAreaComun.UseVisualStyleBackColor = true;
            this.rdoAreaComun.Name = "rdoAreaComun";
            this.rdoAreaComun.TabIndex = 4;
            this.cboUnidadFuncional.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboUnidadFuncional.FormattingEnabled = true;
            this.cboUnidadFuncional.Location = new System.Drawing.Point(120, 94);
            this.cboUnidadFuncional.Size = new System.Drawing.Size(390, 23);
            this.cboUnidadFuncional.Name = "cboUnidadFuncional";
            this.cboUnidadFuncional.TabIndex = 5;
            this.cboUnidadFuncional.SelectedIndexChanged += new System.EventHandler(this.cboUnidadFuncional_SelectedIndexChanged_413BE);
            this.cboAreaComun.Items.AddRange(new object[] {
            "Hall", "Ascensor", "Terraza", "Sala de máquinas", "Cocheras", "Salón de usos múltiples", "Jardín"});
            this.cboAreaComun.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboAreaComun.FormattingEnabled = true;
            this.cboAreaComun.Location = new System.Drawing.Point(120, 94);
            this.cboAreaComun.Size = new System.Drawing.Size(390, 23);
            this.cboAreaComun.Visible = false;
            this.cboAreaComun.Name = "cboAreaComun";
            this.cboAreaComun.TabIndex = 6;
            this.cboAreaComun.SelectedIndexChanged += new System.EventHandler(this.cboAreaComun_SelectedIndexChanged_413BE);
            this.lblConsorcista.AutoSize = true;
            this.lblConsorcista.Location = new System.Drawing.Point(15, 132);
            this.lblConsorcista.Text = "Consorcista";
            this.lblConsorcista.Tag = "lb_car_lblConsorcista";
            this.lblConsorcista.Name = "lblConsorcista";
            this.lblConsorcista.TabIndex = 7;
            this.cboConsorcista.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConsorcista.FormattingEnabled = true;
            this.cboConsorcista.Location = new System.Drawing.Point(120, 128);
            this.cboConsorcista.Size = new System.Drawing.Size(390, 23);
            this.cboConsorcista.Name = "cboConsorcista";
            this.cboConsorcista.TabIndex = 8;
            this.cboConsorcista.SelectedIndexChanged += new System.EventHandler(this.cboConsorcista_SelectedIndexChanged_413BE);
            this.lblCategoria.AutoSize = true;
            this.lblCategoria.Location = new System.Drawing.Point(15, 166);
            this.lblCategoria.Text = "Categoría";
            this.lblCategoria.Tag = "lb_car_lblCategoria";
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.TabIndex = 9;
            this.cboCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategoria.FormattingEnabled = true;
            this.cboCategoria.Location = new System.Drawing.Point(120, 162);
            this.cboCategoria.Size = new System.Drawing.Size(390, 23);
            this.cboCategoria.Name = "cboCategoria";
            this.cboCategoria.TabIndex = 10;
            this.cboCategoria.SelectedIndexChanged += new System.EventHandler(this.cboCategoria_SelectedIndexChanged_413BE);
            this.lblDescripcion.AutoSize = true;
            this.lblDescripcion.Location = new System.Drawing.Point(15, 200);
            this.lblDescripcion.Text = "Descripción";
            this.lblDescripcion.Tag = "lb_car_lblDescripcion";
            this.lblDescripcion.Name = "lblDescripcion";
            this.lblDescripcion.TabIndex = 11;
            this.txtDescripcion.Location = new System.Drawing.Point(120, 196);
            this.txtDescripcion.Size = new System.Drawing.Size(390, 70);
            this.txtDescripcion.Multiline = true;
            this.txtDescripcion.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDescripcion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtDescripcion.Name = "txtDescripcion";
            this.txtDescripcion.TabIndex = 12;
            this.txtDescripcion.TextChanged += new System.EventHandler(this.txtDescripcion_TextChanged_413BE);
            this.lblFotos.AutoSize = true;
            this.lblFotos.Location = new System.Drawing.Point(15, 280);
            this.lblFotos.Text = "Fotos (opcional)";
            this.lblFotos.Tag = "lb_car_lblFotos";
            this.lblFotos.Name = "lblFotos";
            this.lblFotos.TabIndex = 13;
            this.lstFotos.FormattingEnabled = true;
            this.lstFotos.ItemHeight = 15;
            this.lstFotos.Location = new System.Drawing.Point(120, 276);
            this.lstFotos.Size = new System.Drawing.Size(290, 49);
            this.lstFotos.Name = "lstFotos";
            this.lstFotos.TabIndex = 14;
            this.btnAdjuntarFoto.Location = new System.Drawing.Point(420, 276);
            this.btnAdjuntarFoto.Size = new System.Drawing.Size(90, 27);
            this.btnAdjuntarFoto.Text = "Adjuntar foto";
            this.btnAdjuntarFoto.Tag = "btn_car_btnAdjuntarFoto";
            this.btnAdjuntarFoto.UseVisualStyleBackColor = true;
            this.btnAdjuntarFoto.Name = "btnAdjuntarFoto";
            this.btnAdjuntarFoto.TabIndex = 15;
            this.btnAdjuntarFoto.Click += new System.EventHandler(this.btnAdjuntarFoto_Click_413BE);
            this.btnGuardar.Location = new System.Drawing.Point(420, 312);
            this.btnGuardar.Size = new System.Drawing.Size(90, 28);
            this.btnGuardar.Text = "Guardar";
            this.btnGuardar.Tag = "btn_car_btnGuardar";
            this.btnGuardar.UseVisualStyleBackColor = true;
            this.btnGuardar.Enabled = false;
            this.btnGuardar.Name = "btnGuardar";
            this.btnGuardar.TabIndex = 16;
            this.btnGuardar.Click += new System.EventHandler(this.btnGuardar_Click_413BE);
            this.dlgFoto.Filter = "Imágenes|*.jpg;*.jpeg;*.png;*.bmp";
            this.grpPendientes.Controls.Add(this.dgvPendientes);
            this.grpPendientes.Size = new System.Drawing.Size(532, 350);
            this.grpPendientes.TabStop = false;
            this.grpPendientes.Text = "Reclamos pendientes de clasificación";
            this.grpPendientes.Tag = "grp_car_grpPendientes";
            this.grpPendientes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpPendientes.Name = "grpPendientes";
            this.grpPendientes.TabIndex = 1;
            this.dgvPendientes.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvPendientesColId, this.dgvPendientesColFechaAlta, this.dgvPendientesColConsorcio, this.dgvPendientesColUbicacion, this.dgvPendientesColCategoria, this.dgvPendientesColEstado});
            this.dgvPendientes.AllowUserToAddRows = false;
            this.dgvPendientes.AllowUserToDeleteRows = false;
            this.dgvPendientes.AllowUserToResizeRows = false;
            this.dgvPendientes.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvPendientes.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvPendientes.MultiSelect = false;
            this.dgvPendientes.ReadOnly = true;
            this.dgvPendientes.RowHeadersVisible = false;
            this.dgvPendientes.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvPendientes.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvPendientes.Size = new System.Drawing.Size(520, 320);
            this.dgvPendientes.Name = "dgvPendientes";
            this.dgvPendientes.TabIndex = 0;
            this.dgvPendientes.SelectionChanged += new System.EventHandler(this.dgvPendientes_SelectionChanged_413BE);
            this.dgvPendientesColId.HeaderText = "Id";
            this.dgvPendientesColId.Tag = "col_car_dgvPendientesColId";
            this.dgvPendientesColId.Name = "dgvPendientesColId";
            this.dgvPendientesColId.ReadOnly = true;
            this.dgvPendientesColId.FillWeight = 30F;
            this.dgvPendientesColFechaAlta.HeaderText = "Fecha de alta";
            this.dgvPendientesColFechaAlta.Tag = "col_car_dgvPendientesColFechaAlta";
            this.dgvPendientesColFechaAlta.Name = "dgvPendientesColFechaAlta";
            this.dgvPendientesColFechaAlta.ReadOnly = true;
            this.dgvPendientesColFechaAlta.FillWeight = 60F;
            this.dgvPendientesColConsorcio.HeaderText = "Consorcio";
            this.dgvPendientesColConsorcio.Tag = "col_car_dgvPendientesColConsorcio";
            this.dgvPendientesColConsorcio.Name = "dgvPendientesColConsorcio";
            this.dgvPendientesColConsorcio.ReadOnly = true;
            this.dgvPendientesColConsorcio.FillWeight = 90F;
            this.dgvPendientesColUbicacion.HeaderText = "Ubicación";
            this.dgvPendientesColUbicacion.Tag = "col_car_dgvPendientesColUbicacion";
            this.dgvPendientesColUbicacion.Name = "dgvPendientesColUbicacion";
            this.dgvPendientesColUbicacion.ReadOnly = true;
            this.dgvPendientesColUbicacion.FillWeight = 60F;
            this.dgvPendientesColCategoria.HeaderText = "Categoría";
            this.dgvPendientesColCategoria.Tag = "col_car_dgvPendientesColCategoria";
            this.dgvPendientesColCategoria.Name = "dgvPendientesColCategoria";
            this.dgvPendientesColCategoria.ReadOnly = true;
            this.dgvPendientesColCategoria.FillWeight = 60F;
            this.dgvPendientesColEstado.HeaderText = "Estado";
            this.dgvPendientesColEstado.Tag = "col_car_dgvPendientesColEstado";
            this.dgvPendientesColEstado.Name = "dgvPendientesColEstado";
            this.dgvPendientesColEstado.ReadOnly = true;
            this.dgvPendientesColEstado.FillWeight = 90F;
            this.grpClasificacion.Controls.Add(this.lblDatosReclamo);
            this.grpClasificacion.Controls.Add(this.txtDatosReclamo);
            this.grpClasificacion.Controls.Add(this.lblCategoriaClasificacion);
            this.grpClasificacion.Controls.Add(this.cboCategoriaClasificacion);
            this.grpClasificacion.Controls.Add(this.lblTipoImputacion);
            this.grpClasificacion.Controls.Add(this.cboTipoImputacion);
            this.grpClasificacion.Controls.Add(this.lblPrioridad);
            this.grpClasificacion.Controls.Add(this.cboPrioridad);
            this.grpClasificacion.Controls.Add(this.btnClasificar);
            this.grpClasificacion.Size = new System.Drawing.Size(1076, 316);
            this.grpClasificacion.TabStop = false;
            this.grpClasificacion.Text = "Clasificar reclamo";
            this.grpClasificacion.Tag = "grp_car_grpClasificacion";
            this.grpClasificacion.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpClasificacion.Name = "grpClasificacion";
            this.grpClasificacion.TabIndex = 2;
            this.lblDatosReclamo.AutoSize = true;
            this.lblDatosReclamo.Location = new System.Drawing.Point(15, 30);
            this.lblDatosReclamo.Text = "Datos del reclamo";
            this.lblDatosReclamo.Tag = "lb_car_lblDatosReclamo";
            this.lblDatosReclamo.Name = "lblDatosReclamo";
            this.lblDatosReclamo.TabIndex = 0;
            this.txtDatosReclamo.Location = new System.Drawing.Point(15, 50);
            this.txtDatosReclamo.Size = new System.Drawing.Size(1046, 120);
            this.txtDatosReclamo.Multiline = true;
            this.txtDatosReclamo.ScrollBars = System.Windows.Forms.ScrollBars.Vertical;
            this.txtDatosReclamo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtDatosReclamo.ReadOnly = true;
            this.txtDatosReclamo.Name = "txtDatosReclamo";
            this.txtDatosReclamo.TabIndex = 1;
            this.lblCategoriaClasificacion.AutoSize = true;
            this.lblCategoriaClasificacion.Location = new System.Drawing.Point(15, 190);
            this.lblCategoriaClasificacion.Text = "Categoría";
            this.lblCategoriaClasificacion.Tag = "lb_car_lblCategoriaClasificacion";
            this.lblCategoriaClasificacion.Name = "lblCategoriaClasificacion";
            this.lblCategoriaClasificacion.TabIndex = 2;
            this.cboCategoriaClasificacion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategoriaClasificacion.FormattingEnabled = true;
            this.cboCategoriaClasificacion.Location = new System.Drawing.Point(15, 210);
            this.cboCategoriaClasificacion.Size = new System.Drawing.Size(300, 23);
            this.cboCategoriaClasificacion.Name = "cboCategoriaClasificacion";
            this.cboCategoriaClasificacion.TabIndex = 3;
            this.cboCategoriaClasificacion.SelectedIndexChanged += new System.EventHandler(this.cboCategoriaClasificacion_SelectedIndexChanged_413BE);
            this.lblTipoImputacion.AutoSize = true;
            this.lblTipoImputacion.Location = new System.Drawing.Point(340, 190);
            this.lblTipoImputacion.Text = "Tipo de imputación";
            this.lblTipoImputacion.Tag = "lb_car_lblTipoImputacion";
            this.lblTipoImputacion.Name = "lblTipoImputacion";
            this.lblTipoImputacion.TabIndex = 4;
            this.cboTipoImputacion.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTipoImputacion.FormattingEnabled = true;
            this.cboTipoImputacion.Location = new System.Drawing.Point(340, 210);
            this.cboTipoImputacion.Size = new System.Drawing.Size(200, 23);
            this.cboTipoImputacion.Name = "cboTipoImputacion";
            this.cboTipoImputacion.TabIndex = 5;
            this.cboTipoImputacion.SelectedIndexChanged += new System.EventHandler(this.cboTipoImputacion_SelectedIndexChanged_413BE);
            this.lblPrioridad.AutoSize = true;
            this.lblPrioridad.Location = new System.Drawing.Point(565, 190);
            this.lblPrioridad.Text = "Prioridad";
            this.lblPrioridad.Tag = "lb_car_lblPrioridad";
            this.lblPrioridad.Name = "lblPrioridad";
            this.lblPrioridad.TabIndex = 6;
            this.cboPrioridad.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboPrioridad.FormattingEnabled = true;
            this.cboPrioridad.Location = new System.Drawing.Point(565, 210);
            this.cboPrioridad.Size = new System.Drawing.Size(200, 23);
            this.cboPrioridad.Name = "cboPrioridad";
            this.cboPrioridad.TabIndex = 7;
            this.cboPrioridad.SelectedIndexChanged += new System.EventHandler(this.cboPrioridad_SelectedIndexChanged_413BE);
            this.btnClasificar.Location = new System.Drawing.Point(800, 208);
            this.btnClasificar.Size = new System.Drawing.Size(120, 28);
            this.btnClasificar.Text = "Clasificar";
            this.btnClasificar.Tag = "btn_car_btnClasificar";
            this.btnClasificar.UseVisualStyleBackColor = true;
            this.btnClasificar.Enabled = false;
            this.btnClasificar.Name = "btnClasificar";
            this.btnClasificar.TabIndex = 8;
            this.btnClasificar.Click += new System.EventHandler(this.btnClasificar_Click_413BE);
            this.lbReclamoRegistrado.AutoSize = true;
            this.lbReclamoRegistrado.Location = new System.Drawing.Point(3, 3);
            this.lbReclamoRegistrado.Name = "lbReclamoRegistrado";
            this.lbReclamoRegistrado.Size = new System.Drawing.Size(120, 15);
            this.lbReclamoRegistrado.TabIndex = 100;
            this.lbReclamoRegistrado.Tag = "lb_car_reclamoRegistrado";
            this.lbReclamoRegistrado.Text = "Reclamo registrado";
            this.lbReclamoRegistrado.Visible = false;
            this.lbConfirmarReincidencia.AutoSize = true;
            this.lbConfirmarReincidencia.Location = new System.Drawing.Point(3, 20);
            this.lbConfirmarReincidencia.Name = "lbConfirmarReincidencia";
            this.lbConfirmarReincidencia.Size = new System.Drawing.Size(120, 15);
            this.lbConfirmarReincidencia.TabIndex = 101;
            this.lbConfirmarReincidencia.Tag = "lb_car_confirmarReincidencia";
            this.lbConfirmarReincidencia.Text = "Existe un reclamo cerrado hace menos de 30 días con la misma ubicación y catego" +
    "ría (N.º {0}). ¿Se trata del mismo problema?";
            this.lbConfirmarReincidencia.Visible = false;
            this.lbReclamoClasificado.AutoSize = true;
            this.lbReclamoClasificado.Location = new System.Drawing.Point(3, 37);
            this.lbReclamoClasificado.Name = "lbReclamoClasificado";
            this.lbReclamoClasificado.Size = new System.Drawing.Size(120, 15);
            this.lbReclamoClasificado.TabIndex = 102;
            this.lbReclamoClasificado.Tag = "lb_car_reclamoClasificado";
            this.lbReclamoClasificado.Text = "Reclamo clasificado";
            this.lbReclamoClasificado.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.tlpPrincipal);
            this.Controls.Add(this.lbReclamoRegistrado);
            this.Controls.Add(this.lbConfirmarReincidencia);
            this.Controls.Add(this.lbReclamoClasificado);
            this.MinimumSize = new System.Drawing.Size(1120, 740);
            this.Name = "frmCargarClasificarReclamo_413BE";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Cargar y clasificar reclamo";
            this.Load += new System.EventHandler(this.frmCargarClasificarReclamo_Load_413BE);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmCargarClasificarReclamo_FormClosing_413BE);
            ((System.ComponentModel.ISupportInitialize)(this.dgvPendientes)).EndInit();
            this.tlpPrincipal.ResumeLayout(false);
            this.grpCarga.ResumeLayout(false);
            this.grpCarga.PerformLayout();
            this.grpPendientes.ResumeLayout(false);
            this.grpPendientes.PerformLayout();
            this.grpClasificacion.ResumeLayout(false);
            this.grpClasificacion.PerformLayout();
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpPrincipal;
        private System.Windows.Forms.GroupBox grpCarga;
        private System.Windows.Forms.Label lblConsorcio;
        private System.Windows.Forms.ComboBox cboConsorcio;
        private System.Windows.Forms.Label lblUbicacion;
        private System.Windows.Forms.RadioButton rdoUnidadFuncional;
        private System.Windows.Forms.RadioButton rdoAreaComun;
        private System.Windows.Forms.ComboBox cboUnidadFuncional;
        private System.Windows.Forms.ComboBox cboAreaComun;
        private System.Windows.Forms.Label lblConsorcista;
        private System.Windows.Forms.ComboBox cboConsorcista;
        private System.Windows.Forms.Label lblCategoria;
        private System.Windows.Forms.ComboBox cboCategoria;
        private System.Windows.Forms.Label lblDescripcion;
        private System.Windows.Forms.TextBox txtDescripcion;
        private System.Windows.Forms.Label lblFotos;
        private System.Windows.Forms.ListBox lstFotos;
        private System.Windows.Forms.Button btnAdjuntarFoto;
        private System.Windows.Forms.Button btnGuardar;
        private System.Windows.Forms.OpenFileDialog dlgFoto;
        private System.Windows.Forms.GroupBox grpPendientes;
        private System.Windows.Forms.DataGridView dgvPendientes;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColFechaAlta;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColConsorcio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColUbicacion;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColCategoria;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvPendientesColEstado;
        private System.Windows.Forms.GroupBox grpClasificacion;
        private System.Windows.Forms.Label lblDatosReclamo;
        private System.Windows.Forms.TextBox txtDatosReclamo;
        private System.Windows.Forms.Label lblCategoriaClasificacion;
        private System.Windows.Forms.ComboBox cboCategoriaClasificacion;
        private System.Windows.Forms.Label lblTipoImputacion;
        private System.Windows.Forms.ComboBox cboTipoImputacion;
        private System.Windows.Forms.Label lblPrioridad;
        private System.Windows.Forms.ComboBox cboPrioridad;
        private System.Windows.Forms.Button btnClasificar;
        private System.Windows.Forms.Label lbReclamoRegistrado;
        private System.Windows.Forms.Label lbConfirmarReincidencia;
        private System.Windows.Forms.Label lbReclamoClasificado;
    }
}
