namespace AppBase
{
    partial class frmHistorialReclamos_413BE
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tlpPrincipal = new System.Windows.Forms.TableLayoutPanel();
            this.grpFiltros = new System.Windows.Forms.GroupBox();
            this.lblConsorcio = new System.Windows.Forms.Label();
            this.cboConsorcio = new System.Windows.Forms.ComboBox();
            this.lblProveedor = new System.Windows.Forms.Label();
            this.cboProveedor = new System.Windows.Forms.ComboBox();
            this.lblCategoria = new System.Windows.Forms.Label();
            this.cboCategoria = new System.Windows.Forms.ComboBox();
            this.lblEstado = new System.Windows.Forms.Label();
            this.cboEstado = new System.Windows.Forms.ComboBox();
            this.lblDesde = new System.Windows.Forms.Label();
            this.dtpDesde = new System.Windows.Forms.DateTimePicker();
            this.lblHasta = new System.Windows.Forms.Label();
            this.dtpHasta = new System.Windows.Forms.DateTimePicker();
            this.btnFiltrar = new System.Windows.Forms.Button();
            this.grpHistorial = new System.Windows.Forms.GroupBox();
            this.dgvReclamos = new System.Windows.Forms.DataGridView();
            this.dgvReclamosColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColFechaAlta = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColConsorcio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColCategoria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColEstado = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColPrioridad = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColTipoImputacion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColReincidente = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvReclamosColDescripcion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.pnlHistorialPie = new System.Windows.Forms.Panel();
            this.btnExportarHistorial = new System.Windows.Forms.Button();
            this.grpDesempeno = new System.Windows.Forms.GroupBox();
            this.dgvDesempeno = new System.Windows.Forms.DataGridView();
            this.dgvDesempenoColProveedor = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDesempenoColCategoria = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDesempenoColPrecioPromedio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDesempenoColTiempoPromedio = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDesempenoColTasaReincidencia = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvDesempenoColReclamosResueltos = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.pnlDesempenoPie = new System.Windows.Forms.Panel();
            this.btnExportarDesempeno = new System.Windows.Forms.Button();
            this.pnlDesempenoTop = new System.Windows.Forms.Panel();
            this.lblProveedorDesempeno = new System.Windows.Forms.Label();
            this.cboProveedorDesempeno = new System.Windows.Forms.ComboBox();
            this.btnVerDesempeno = new System.Windows.Forms.Button();
            this.dlgGuardarPdf = new System.Windows.Forms.SaveFileDialog();
            this.lbPdfGenerado = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgvReclamos)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDesempeno)).BeginInit();
            this.tlpPrincipal.SuspendLayout();
            this.grpFiltros.SuspendLayout();
            this.grpHistorial.SuspendLayout();
            this.pnlHistorialPie.SuspendLayout();
            this.grpDesempeno.SuspendLayout();
            this.pnlDesempenoPie.SuspendLayout();
            this.pnlDesempenoTop.SuspendLayout();
            this.SuspendLayout();
            this.tlpPrincipal.Controls.Add(this.grpFiltros, 0, 0);
            this.tlpPrincipal.Controls.Add(this.grpHistorial, 0, 1);
            this.tlpPrincipal.Controls.Add(this.grpDesempeno, 0, 2);
            this.tlpPrincipal.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Absolute, 135F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 55F));
            this.tlpPrincipal.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 45F));
            this.tlpPrincipal.ColumnCount = 1;
            this.tlpPrincipal.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpPrincipal.RowCount = 3;
            this.tlpPrincipal.Padding = new System.Windows.Forms.Padding(9);
            this.tlpPrincipal.Name = "tlpPrincipal";
            this.tlpPrincipal.TabIndex = 0;
            this.grpFiltros.Controls.Add(this.lblConsorcio);
            this.grpFiltros.Controls.Add(this.cboConsorcio);
            this.grpFiltros.Controls.Add(this.lblProveedor);
            this.grpFiltros.Controls.Add(this.cboProveedor);
            this.grpFiltros.Controls.Add(this.lblCategoria);
            this.grpFiltros.Controls.Add(this.cboCategoria);
            this.grpFiltros.Controls.Add(this.lblEstado);
            this.grpFiltros.Controls.Add(this.cboEstado);
            this.grpFiltros.Controls.Add(this.lblDesde);
            this.grpFiltros.Controls.Add(this.dtpDesde);
            this.grpFiltros.Controls.Add(this.lblHasta);
            this.grpFiltros.Controls.Add(this.dtpHasta);
            this.grpFiltros.Controls.Add(this.btnFiltrar);
            this.grpFiltros.Size = new System.Drawing.Size(1076, 135);
            this.grpFiltros.TabStop = false;
            this.grpFiltros.Text = "Filtros";
            this.grpFiltros.Tag = "grp_his_grpFiltros";
            this.grpFiltros.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpFiltros.Name = "grpFiltros";
            this.grpFiltros.TabIndex = 0;
            this.lblConsorcio.AutoSize = true;
            this.lblConsorcio.Location = new System.Drawing.Point(15, 24);
            this.lblConsorcio.Text = "Consorcio";
            this.lblConsorcio.Tag = "lb_his_lblConsorcio";
            this.lblConsorcio.Name = "lblConsorcio";
            this.lblConsorcio.TabIndex = 0;
            this.cboConsorcio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConsorcio.FormattingEnabled = true;
            this.cboConsorcio.Location = new System.Drawing.Point(15, 44);
            this.cboConsorcio.Size = new System.Drawing.Size(220, 23);
            this.cboConsorcio.Name = "cboConsorcio";
            this.cboConsorcio.TabIndex = 1;
            this.lblProveedor.AutoSize = true;
            this.lblProveedor.Location = new System.Drawing.Point(250, 24);
            this.lblProveedor.Text = "Proveedor";
            this.lblProveedor.Tag = "lb_his_lblProveedor";
            this.lblProveedor.Name = "lblProveedor";
            this.lblProveedor.TabIndex = 2;
            this.cboProveedor.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboProveedor.FormattingEnabled = true;
            this.cboProveedor.Location = new System.Drawing.Point(250, 44);
            this.cboProveedor.Size = new System.Drawing.Size(220, 23);
            this.cboProveedor.Name = "cboProveedor";
            this.cboProveedor.TabIndex = 3;
            this.lblCategoria.AutoSize = true;
            this.lblCategoria.Location = new System.Drawing.Point(485, 24);
            this.lblCategoria.Text = "Categoría";
            this.lblCategoria.Tag = "lb_his_lblCategoria";
            this.lblCategoria.Name = "lblCategoria";
            this.lblCategoria.TabIndex = 4;
            this.cboCategoria.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboCategoria.FormattingEnabled = true;
            this.cboCategoria.Location = new System.Drawing.Point(485, 44);
            this.cboCategoria.Size = new System.Drawing.Size(180, 23);
            this.cboCategoria.Name = "cboCategoria";
            this.cboCategoria.TabIndex = 5;
            this.lblEstado.AutoSize = true;
            this.lblEstado.Location = new System.Drawing.Point(680, 24);
            this.lblEstado.Text = "Estado";
            this.lblEstado.Tag = "lb_his_lblEstado";
            this.lblEstado.Name = "lblEstado";
            this.lblEstado.TabIndex = 6;
            this.cboEstado.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboEstado.FormattingEnabled = true;
            this.cboEstado.Location = new System.Drawing.Point(680, 44);
            this.cboEstado.Size = new System.Drawing.Size(200, 23);
            this.cboEstado.Name = "cboEstado";
            this.cboEstado.TabIndex = 7;
            this.lblDesde.AutoSize = true;
            this.lblDesde.Location = new System.Drawing.Point(15, 78);
            this.lblDesde.Text = "Desde";
            this.lblDesde.Tag = "lb_his_lblDesde";
            this.lblDesde.Name = "lblDesde";
            this.lblDesde.TabIndex = 8;
            this.dtpDesde.Checked = false;
            this.dtpDesde.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpDesde.Location = new System.Drawing.Point(15, 98);
            this.dtpDesde.ShowCheckBox = true;
            this.dtpDesde.Size = new System.Drawing.Size(220, 23);
            this.dtpDesde.Name = "dtpDesde";
            this.dtpDesde.TabIndex = 9;
            this.lblHasta.AutoSize = true;
            this.lblHasta.Location = new System.Drawing.Point(250, 78);
            this.lblHasta.Text = "Hasta";
            this.lblHasta.Tag = "lb_his_lblHasta";
            this.lblHasta.Name = "lblHasta";
            this.lblHasta.TabIndex = 10;
            this.dtpHasta.Checked = false;
            this.dtpHasta.Format = System.Windows.Forms.DateTimePickerFormat.Short;
            this.dtpHasta.Location = new System.Drawing.Point(250, 98);
            this.dtpHasta.ShowCheckBox = true;
            this.dtpHasta.Size = new System.Drawing.Size(220, 23);
            this.dtpHasta.Name = "dtpHasta";
            this.dtpHasta.TabIndex = 11;
            this.btnFiltrar.Location = new System.Drawing.Point(485, 96);
            this.btnFiltrar.Size = new System.Drawing.Size(100, 28);
            this.btnFiltrar.Text = "Filtrar";
            this.btnFiltrar.Tag = "btn_his_btnFiltrar";
            this.btnFiltrar.UseVisualStyleBackColor = true;
            this.btnFiltrar.Name = "btnFiltrar";
            this.btnFiltrar.TabIndex = 12;
            this.btnFiltrar.Click += new System.EventHandler(this.btnFiltrar_Click_413BE);
            this.grpHistorial.Controls.Add(this.dgvReclamos);
            this.grpHistorial.Controls.Add(this.pnlHistorialPie);
            this.grpHistorial.Size = new System.Drawing.Size(1076, 270);
            this.grpHistorial.TabStop = false;
            this.grpHistorial.Text = "Historial de reclamos";
            this.grpHistorial.Tag = "grp_his_grpHistorial";
            this.grpHistorial.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpHistorial.Name = "grpHistorial";
            this.grpHistorial.TabIndex = 1;
            this.dgvReclamos.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvReclamosColId, this.dgvReclamosColFechaAlta, this.dgvReclamosColConsorcio, this.dgvReclamosColCategoria, this.dgvReclamosColEstado, this.dgvReclamosColPrioridad, this.dgvReclamosColTipoImputacion, this.dgvReclamosColReincidente, this.dgvReclamosColDescripcion});
            this.dgvReclamos.AllowUserToAddRows = false;
            this.dgvReclamos.AllowUserToDeleteRows = false;
            this.dgvReclamos.AllowUserToResizeRows = false;
            this.dgvReclamos.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvReclamos.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvReclamos.MultiSelect = false;
            this.dgvReclamos.ReadOnly = true;
            this.dgvReclamos.RowHeadersVisible = false;
            this.dgvReclamos.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvReclamos.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvReclamos.Size = new System.Drawing.Size(1056, 200);
            this.dgvReclamos.Name = "dgvReclamos";
            this.dgvReclamos.TabIndex = 0;
            this.dgvReclamosColId.HeaderText = "Id";
            this.dgvReclamosColId.Tag = "col_his_dgvReclamosColId";
            this.dgvReclamosColId.Name = "dgvReclamosColId";
            this.dgvReclamosColId.ReadOnly = true;
            this.dgvReclamosColId.FillWeight = 30F;
            this.dgvReclamosColFechaAlta.HeaderText = "Fecha de alta";
            this.dgvReclamosColFechaAlta.Tag = "col_his_dgvReclamosColFechaAlta";
            this.dgvReclamosColFechaAlta.Name = "dgvReclamosColFechaAlta";
            this.dgvReclamosColFechaAlta.ReadOnly = true;
            this.dgvReclamosColFechaAlta.FillWeight = 60F;
            this.dgvReclamosColConsorcio.HeaderText = "Consorcio";
            this.dgvReclamosColConsorcio.Tag = "col_his_dgvReclamosColConsorcio";
            this.dgvReclamosColConsorcio.Name = "dgvReclamosColConsorcio";
            this.dgvReclamosColConsorcio.ReadOnly = true;
            this.dgvReclamosColConsorcio.FillWeight = 90F;
            this.dgvReclamosColCategoria.HeaderText = "Categoría";
            this.dgvReclamosColCategoria.Tag = "col_his_dgvReclamosColCategoria";
            this.dgvReclamosColCategoria.Name = "dgvReclamosColCategoria";
            this.dgvReclamosColCategoria.ReadOnly = true;
            this.dgvReclamosColCategoria.FillWeight = 60F;
            this.dgvReclamosColEstado.HeaderText = "Estado";
            this.dgvReclamosColEstado.Tag = "col_his_dgvReclamosColEstado";
            this.dgvReclamosColEstado.Name = "dgvReclamosColEstado";
            this.dgvReclamosColEstado.ReadOnly = true;
            this.dgvReclamosColEstado.FillWeight = 80F;
            this.dgvReclamosColPrioridad.HeaderText = "Prioridad";
            this.dgvReclamosColPrioridad.Tag = "col_his_dgvReclamosColPrioridad";
            this.dgvReclamosColPrioridad.Name = "dgvReclamosColPrioridad";
            this.dgvReclamosColPrioridad.ReadOnly = true;
            this.dgvReclamosColPrioridad.FillWeight = 50F;
            this.dgvReclamosColTipoImputacion.HeaderText = "Tipo de imputación";
            this.dgvReclamosColTipoImputacion.Tag = "col_his_dgvReclamosColTipoImputacion";
            this.dgvReclamosColTipoImputacion.Name = "dgvReclamosColTipoImputacion";
            this.dgvReclamosColTipoImputacion.ReadOnly = true;
            this.dgvReclamosColTipoImputacion.FillWeight = 60F;
            this.dgvReclamosColReincidente.HeaderText = "Reincidente";
            this.dgvReclamosColReincidente.Tag = "col_his_dgvReclamosColReincidente";
            this.dgvReclamosColReincidente.Name = "dgvReclamosColReincidente";
            this.dgvReclamosColReincidente.ReadOnly = true;
            this.dgvReclamosColReincidente.FillWeight = 50F;
            this.dgvReclamosColDescripcion.HeaderText = "Descripción";
            this.dgvReclamosColDescripcion.Tag = "col_his_dgvReclamosColDescripcion";
            this.dgvReclamosColDescripcion.Name = "dgvReclamosColDescripcion";
            this.dgvReclamosColDescripcion.ReadOnly = true;
            this.dgvReclamosColDescripcion.FillWeight = 150F;
            this.pnlHistorialPie.Controls.Add(this.btnExportarHistorial);
            this.pnlHistorialPie.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlHistorialPie.Size = new System.Drawing.Size(1064, 36);
            this.pnlHistorialPie.Name = "pnlHistorialPie";
            this.pnlHistorialPie.TabIndex = 1;
            this.btnExportarHistorial.Location = new System.Drawing.Point(6, 4);
            this.btnExportarHistorial.Size = new System.Drawing.Size(140, 28);
            this.btnExportarHistorial.Text = "Exportar historial";
            this.btnExportarHistorial.Tag = "btn_his_btnExportarHistorial";
            this.btnExportarHistorial.UseVisualStyleBackColor = true;
            this.btnExportarHistorial.Name = "btnExportarHistorial";
            this.btnExportarHistorial.TabIndex = 0;
            this.btnExportarHistorial.Click += new System.EventHandler(this.btnExportarHistorial_Click_413BE);
            this.grpDesempeno.Controls.Add(this.dgvDesempeno);
            this.grpDesempeno.Controls.Add(this.pnlDesempenoPie);
            this.grpDesempeno.Controls.Add(this.pnlDesempenoTop);
            this.grpDesempeno.Size = new System.Drawing.Size(1076, 255);
            this.grpDesempeno.TabStop = false;
            this.grpDesempeno.Text = "Desempeño histórico por proveedor";
            this.grpDesempeno.Tag = "grp_his_grpDesempeno";
            this.grpDesempeno.Dock = System.Windows.Forms.DockStyle.Fill;
            this.grpDesempeno.Name = "grpDesempeno";
            this.grpDesempeno.TabIndex = 2;
            this.dgvDesempeno.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvDesempenoColProveedor, this.dgvDesempenoColCategoria, this.dgvDesempenoColPrecioPromedio, this.dgvDesempenoColTiempoPromedio, this.dgvDesempenoColTasaReincidencia, this.dgvDesempenoColReclamosResueltos});
            this.dgvDesempeno.AllowUserToAddRows = false;
            this.dgvDesempeno.AllowUserToDeleteRows = false;
            this.dgvDesempeno.AllowUserToResizeRows = false;
            this.dgvDesempeno.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvDesempeno.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvDesempeno.MultiSelect = false;
            this.dgvDesempeno.ReadOnly = true;
            this.dgvDesempeno.RowHeadersVisible = false;
            this.dgvDesempeno.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvDesempeno.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvDesempeno.Size = new System.Drawing.Size(1056, 155);
            this.dgvDesempeno.Name = "dgvDesempeno";
            this.dgvDesempeno.TabIndex = 0;
            this.dgvDesempenoColProveedor.HeaderText = "Proveedor";
            this.dgvDesempenoColProveedor.Tag = "col_his_dgvDesempenoColProveedor";
            this.dgvDesempenoColProveedor.Name = "dgvDesempenoColProveedor";
            this.dgvDesempenoColProveedor.ReadOnly = true;
            this.dgvDesempenoColProveedor.FillWeight = 100F;
            this.dgvDesempenoColCategoria.HeaderText = "Categoría";
            this.dgvDesempenoColCategoria.Tag = "col_his_dgvDesempenoColCategoria";
            this.dgvDesempenoColCategoria.Name = "dgvDesempenoColCategoria";
            this.dgvDesempenoColCategoria.ReadOnly = true;
            this.dgvDesempenoColCategoria.FillWeight = 70F;
            this.dgvDesempenoColPrecioPromedio.HeaderText = "Precio promedio";
            this.dgvDesempenoColPrecioPromedio.Tag = "col_his_dgvDesempenoColPrecioPromedio";
            this.dgvDesempenoColPrecioPromedio.Name = "dgvDesempenoColPrecioPromedio";
            this.dgvDesempenoColPrecioPromedio.ReadOnly = true;
            this.dgvDesempenoColPrecioPromedio.FillWeight = 60F;
            this.dgvDesempenoColTiempoPromedio.HeaderText = "Tiempo promedio (días)";
            this.dgvDesempenoColTiempoPromedio.Tag = "col_his_dgvDesempenoColTiempoPromedio";
            this.dgvDesempenoColTiempoPromedio.Name = "dgvDesempenoColTiempoPromedio";
            this.dgvDesempenoColTiempoPromedio.ReadOnly = true;
            this.dgvDesempenoColTiempoPromedio.FillWeight = 60F;
            this.dgvDesempenoColTasaReincidencia.HeaderText = "Tasa de reincidencia (%)";
            this.dgvDesempenoColTasaReincidencia.Tag = "col_his_dgvDesempenoColTasaReincidencia";
            this.dgvDesempenoColTasaReincidencia.Name = "dgvDesempenoColTasaReincidencia";
            this.dgvDesempenoColTasaReincidencia.ReadOnly = true;
            this.dgvDesempenoColTasaReincidencia.FillWeight = 60F;
            this.dgvDesempenoColReclamosResueltos.HeaderText = "Reclamos resueltos";
            this.dgvDesempenoColReclamosResueltos.Tag = "col_his_dgvDesempenoColReclamosResueltos";
            this.dgvDesempenoColReclamosResueltos.Name = "dgvDesempenoColReclamosResueltos";
            this.dgvDesempenoColReclamosResueltos.ReadOnly = true;
            this.dgvDesempenoColReclamosResueltos.FillWeight = 50F;
            this.pnlDesempenoPie.Controls.Add(this.btnExportarDesempeno);
            this.pnlDesempenoPie.Dock = System.Windows.Forms.DockStyle.Bottom;
            this.pnlDesempenoPie.Size = new System.Drawing.Size(1064, 36);
            this.pnlDesempenoPie.Name = "pnlDesempenoPie";
            this.pnlDesempenoPie.TabIndex = 1;
            this.btnExportarDesempeno.Location = new System.Drawing.Point(6, 4);
            this.btnExportarDesempeno.Size = new System.Drawing.Size(150, 28);
            this.btnExportarDesempeno.Text = "Exportar desempeño";
            this.btnExportarDesempeno.Tag = "btn_his_btnExportarDesempeno";
            this.btnExportarDesempeno.UseVisualStyleBackColor = true;
            this.btnExportarDesempeno.Enabled = false;
            this.btnExportarDesempeno.Name = "btnExportarDesempeno";
            this.btnExportarDesempeno.TabIndex = 0;
            this.btnExportarDesempeno.Click += new System.EventHandler(this.btnExportarDesempeno_Click_413BE);
            this.pnlDesempenoTop.Controls.Add(this.lblProveedorDesempeno);
            this.pnlDesempenoTop.Controls.Add(this.cboProveedorDesempeno);
            this.pnlDesempenoTop.Controls.Add(this.btnVerDesempeno);
            this.pnlDesempenoTop.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlDesempenoTop.Size = new System.Drawing.Size(1064, 36);
            this.pnlDesempenoTop.Name = "pnlDesempenoTop";
            this.pnlDesempenoTop.TabIndex = 2;
            this.lblProveedorDesempeno.AutoSize = true;
            this.lblProveedorDesempeno.Location = new System.Drawing.Point(6, 9);
            this.lblProveedorDesempeno.Text = "Proveedor";
            this.lblProveedorDesempeno.Tag = "lb_his_lblProveedorDesempeno";
            this.lblProveedorDesempeno.Name = "lblProveedorDesempeno";
            this.lblProveedorDesempeno.TabIndex = 0;
            this.cboProveedorDesempeno.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboProveedorDesempeno.FormattingEnabled = true;
            this.cboProveedorDesempeno.Location = new System.Drawing.Point(90, 5);
            this.cboProveedorDesempeno.Size = new System.Drawing.Size(300, 23);
            this.cboProveedorDesempeno.Name = "cboProveedorDesempeno";
            this.cboProveedorDesempeno.TabIndex = 1;
            this.cboProveedorDesempeno.SelectedIndexChanged += new System.EventHandler(this.cboProveedorDesempeno_SelectedIndexChanged_413BE);
            this.btnVerDesempeno.Location = new System.Drawing.Point(410, 4);
            this.btnVerDesempeno.Size = new System.Drawing.Size(120, 27);
            this.btnVerDesempeno.Text = "Ver desempeño";
            this.btnVerDesempeno.Tag = "btn_his_btnVerDesempeno";
            this.btnVerDesempeno.UseVisualStyleBackColor = true;
            this.btnVerDesempeno.Enabled = false;
            this.btnVerDesempeno.Name = "btnVerDesempeno";
            this.btnVerDesempeno.TabIndex = 2;
            this.btnVerDesempeno.Click += new System.EventHandler(this.btnVerDesempeno_Click_413BE);
            this.dlgGuardarPdf.Filter = "PDF|*.pdf";
            this.lbPdfGenerado.AutoSize = true;
            this.lbPdfGenerado.Location = new System.Drawing.Point(3, 3);
            this.lbPdfGenerado.Name = "lbPdfGenerado";
            this.lbPdfGenerado.Size = new System.Drawing.Size(120, 15);
            this.lbPdfGenerado.TabIndex = 100;
            this.lbPdfGenerado.Tag = "lb_his_pdfGenerado";
            this.lbPdfGenerado.Text = "PDF generado correctamente";
            this.lbPdfGenerado.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.tlpPrincipal);
            this.Controls.Add(this.lbPdfGenerado);
            this.MinimumSize = new System.Drawing.Size(1120, 740);
            this.Name = "frmHistorialReclamos_413BE";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Consultar historial";
            this.Load += new System.EventHandler(this.frmHistorialReclamos_Load_413BE);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmHistorialReclamos_FormClosing_413BE);
            ((System.ComponentModel.ISupportInitialize)(this.dgvReclamos)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvDesempeno)).EndInit();
            this.tlpPrincipal.ResumeLayout(false);
            this.grpFiltros.ResumeLayout(false);
            this.grpFiltros.PerformLayout();
            this.grpHistorial.ResumeLayout(false);
            this.grpHistorial.PerformLayout();
            this.pnlHistorialPie.ResumeLayout(false);
            this.grpDesempeno.ResumeLayout(false);
            this.grpDesempeno.PerformLayout();
            this.pnlDesempenoPie.ResumeLayout(false);
            this.pnlDesempenoTop.ResumeLayout(false);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.TableLayoutPanel tlpPrincipal;
        private System.Windows.Forms.GroupBox grpFiltros;
        private System.Windows.Forms.Label lblConsorcio;
        private System.Windows.Forms.ComboBox cboConsorcio;
        private System.Windows.Forms.Label lblProveedor;
        private System.Windows.Forms.ComboBox cboProveedor;
        private System.Windows.Forms.Label lblCategoria;
        private System.Windows.Forms.ComboBox cboCategoria;
        private System.Windows.Forms.Label lblEstado;
        private System.Windows.Forms.ComboBox cboEstado;
        private System.Windows.Forms.Label lbPdfGenerado;
        private System.Windows.Forms.Label lblDesde;
        private System.Windows.Forms.DateTimePicker dtpDesde;
        private System.Windows.Forms.Label lblHasta;
        private System.Windows.Forms.DateTimePicker dtpHasta;
        private System.Windows.Forms.Button btnFiltrar;
        private System.Windows.Forms.GroupBox grpHistorial;
        private System.Windows.Forms.DataGridView dgvReclamos;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColFechaAlta;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColConsorcio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColCategoria;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColEstado;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColPrioridad;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColTipoImputacion;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColReincidente;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvReclamosColDescripcion;
        private System.Windows.Forms.Panel pnlHistorialPie;
        private System.Windows.Forms.Button btnExportarHistorial;
        private System.Windows.Forms.GroupBox grpDesempeno;
        private System.Windows.Forms.DataGridView dgvDesempeno;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColProveedor;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColCategoria;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColPrecioPromedio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColTiempoPromedio;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColTasaReincidencia;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvDesempenoColReclamosResueltos;
        private System.Windows.Forms.Panel pnlDesempenoPie;
        private System.Windows.Forms.Button btnExportarDesempeno;
        private System.Windows.Forms.Panel pnlDesempenoTop;
        private System.Windows.Forms.Label lblProveedorDesempeno;
        private System.Windows.Forms.ComboBox cboProveedorDesempeno;
        private System.Windows.Forms.Button btnVerDesempeno;
        private System.Windows.Forms.SaveFileDialog dlgGuardarPdf;
    }
}
