namespace AppBase
{
    partial class frmMantenimientoConsorcios_413BE
    {
        private System.ComponentModel.IContainer components = null;

        protected override void Dispose(bool disposing)
        {
            if (disposing && (components != null))
            {
                components.Dispose();
            }
            base.Dispose(disposing);
        }

        #region Windows Form Designer generated code

        private void InitializeComponent()
        {
            this.tabMaestros = new System.Windows.Forms.TabControl();
            this.tpConsorcios = new System.Windows.Forms.TabPage();
            this.tpUnidadesFuncionales = new System.Windows.Forms.TabPage();
            this.tpConsorcistas = new System.Windows.Forms.TabPage();
            this.tlpConsorcios = new System.Windows.Forms.TableLayoutPanel();
            this.dgvConsorcios = new System.Windows.Forms.DataGridView();
            this.dgvConsorciosColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorciosColNombre = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorciosColDireccion = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorciosColCantidadUnidades = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorciosColActivo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.pnlDetalleConsorcio = new System.Windows.Forms.Panel();
            this.lblNombre = new System.Windows.Forms.Label();
            this.txtNombre = new System.Windows.Forms.TextBox();
            this.lblDireccion = new System.Windows.Forms.Label();
            this.txtDireccion = new System.Windows.Forms.TextBox();
            this.lblCantidadUnidades = new System.Windows.Forms.Label();
            this.numCantidadUnidades = new System.Windows.Forms.NumericUpDown();
            this.chkActivo = new System.Windows.Forms.CheckBox();
            this.btnNuevoConsorcio = new System.Windows.Forms.Button();
            this.btnGuardarConsorcio = new System.Windows.Forms.Button();
            this.btnInactivarConsorcio = new System.Windows.Forms.Button();
            this.btnReactivarConsorcio = new System.Windows.Forms.Button();
            this.btnCancelarConsorcio = new System.Windows.Forms.Button();
            this.tlpUnidadesFuncionales = new System.Windows.Forms.TableLayoutPanel();
            this.pnlListaUnidadesFuncionales = new System.Windows.Forms.Panel();
            this.dgvUnidadesFuncionales = new System.Windows.Forms.DataGridView();
            this.dgvUnidadesFuncionalesColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvUnidadesFuncionalesColIdentificador = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvUnidadesFuncionalesColTipo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvUnidadesFuncionalesColActiva = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.pnlFiltroConsorcioUF = new System.Windows.Forms.Panel();
            this.lblConsorcio = new System.Windows.Forms.Label();
            this.cboConsorcio = new System.Windows.Forms.ComboBox();
            this.pnlDetalleUnidadFuncional = new System.Windows.Forms.Panel();
            this.lblIdentificador = new System.Windows.Forms.Label();
            this.txtIdentificador = new System.Windows.Forms.TextBox();
            this.lblTipo = new System.Windows.Forms.Label();
            this.cboTipo = new System.Windows.Forms.ComboBox();
            this.chkActiva = new System.Windows.Forms.CheckBox();
            this.btnNuevoUnidadFuncional = new System.Windows.Forms.Button();
            this.btnGuardarUnidadFuncional = new System.Windows.Forms.Button();
            this.btnInactivarUnidadFuncional = new System.Windows.Forms.Button();
            this.btnReactivarUnidadFuncional = new System.Windows.Forms.Button();
            this.btnCancelarUnidadFuncional = new System.Windows.Forms.Button();
            this.tlpConsorcistas = new System.Windows.Forms.TableLayoutPanel();
            this.pnlListaConsorcistas = new System.Windows.Forms.Panel();
            this.dgvConsorcistas = new System.Windows.Forms.DataGridView();
            this.dgvConsorcistasColId = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorcistasColDni = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorcistasColNombre = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorcistasColEmail = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorcistasColTipo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.dgvConsorcistasColActivo = new System.Windows.Forms.DataGridViewTextBoxColumn();
            this.pnlFiltroConsorcista = new System.Windows.Forms.Panel();
            this.lblConsorcioConsorcista = new System.Windows.Forms.Label();
            this.cboConsorcioConsorcista = new System.Windows.Forms.ComboBox();
            this.lblUnidadFuncionalConsorcista = new System.Windows.Forms.Label();
            this.cboUnidadFuncionalConsorcista = new System.Windows.Forms.ComboBox();
            this.pnlDetalleConsorcista = new System.Windows.Forms.Panel();
            this.lblDni = new System.Windows.Forms.Label();
            this.txtDni = new System.Windows.Forms.TextBox();
            this.lblNombreConsorcista = new System.Windows.Forms.Label();
            this.txtNombreConsorcista = new System.Windows.Forms.TextBox();
            this.lblEmailConsorcista = new System.Windows.Forms.Label();
            this.txtEmailConsorcista = new System.Windows.Forms.TextBox();
            this.rdoPropietario = new System.Windows.Forms.RadioButton();
            this.rdoInquilino = new System.Windows.Forms.RadioButton();
            this.chkActivoConsorcista = new System.Windows.Forms.CheckBox();
            this.btnNuevoConsorcista = new System.Windows.Forms.Button();
            this.btnGuardarConsorcista = new System.Windows.Forms.Button();
            this.btnInactivarConsorcista = new System.Windows.Forms.Button();
            this.btnReactivarConsorcista = new System.Windows.Forms.Button();
            this.btnCancelarConsorcista = new System.Windows.Forms.Button();
            this.lbGuardado = new System.Windows.Forms.Label();
            ((System.ComponentModel.ISupportInitialize)(this.dgvConsorcios)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCantidadUnidades)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvUnidadesFuncionales)).BeginInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvConsorcistas)).BeginInit();
            this.tabMaestros.SuspendLayout();
            this.tpConsorcios.SuspendLayout();
            this.tpUnidadesFuncionales.SuspendLayout();
            this.tpConsorcistas.SuspendLayout();
            this.tlpConsorcios.SuspendLayout();
            this.pnlDetalleConsorcio.SuspendLayout();
            this.tlpUnidadesFuncionales.SuspendLayout();
            this.pnlListaUnidadesFuncionales.SuspendLayout();
            this.pnlFiltroConsorcioUF.SuspendLayout();
            this.pnlDetalleUnidadFuncional.SuspendLayout();
            this.tlpConsorcistas.SuspendLayout();
            this.pnlListaConsorcistas.SuspendLayout();
            this.pnlFiltroConsorcista.SuspendLayout();
            this.pnlDetalleConsorcista.SuspendLayout();
            this.SuspendLayout();
            this.tabMaestros.Controls.Add(this.tpConsorcios);
            this.tabMaestros.Controls.Add(this.tpUnidadesFuncionales);
            this.tabMaestros.Controls.Add(this.tpConsorcistas);
            this.tabMaestros.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tabMaestros.Name = "tabMaestros";
            this.tabMaestros.TabIndex = 0;
            this.tpConsorcios.Controls.Add(this.tlpConsorcios);
            this.tpConsorcios.Location = new System.Drawing.Point(4, 24);
            this.tpConsorcios.Padding = new System.Windows.Forms.Padding(9);
            this.tpConsorcios.Size = new System.Drawing.Size(1080, 700);
            this.tpConsorcios.Text = "Consorcios";
            this.tpConsorcios.Tag = "tab_man_tpConsorcios";
            this.tpConsorcios.UseVisualStyleBackColor = true;
            this.tpConsorcios.Name = "tpConsorcios";
            this.tpConsorcios.TabIndex = 0;
            this.tpUnidadesFuncionales.Controls.Add(this.tlpUnidadesFuncionales);
            this.tpUnidadesFuncionales.Location = new System.Drawing.Point(4, 24);
            this.tpUnidadesFuncionales.Padding = new System.Windows.Forms.Padding(9);
            this.tpUnidadesFuncionales.Size = new System.Drawing.Size(1080, 700);
            this.tpUnidadesFuncionales.Text = "Unidades funcionales";
            this.tpUnidadesFuncionales.Tag = "tab_man_tpUnidadesFuncionales";
            this.tpUnidadesFuncionales.UseVisualStyleBackColor = true;
            this.tpUnidadesFuncionales.Name = "tpUnidadesFuncionales";
            this.tpUnidadesFuncionales.TabIndex = 1;
            this.tpConsorcistas.Controls.Add(this.tlpConsorcistas);
            this.tpConsorcistas.Location = new System.Drawing.Point(4, 24);
            this.tpConsorcistas.Padding = new System.Windows.Forms.Padding(9);
            this.tpConsorcistas.Size = new System.Drawing.Size(1080, 700);
            this.tpConsorcistas.Text = "Consorcistas";
            this.tpConsorcistas.Tag = "tab_man_tpConsorcistas";
            this.tpConsorcistas.UseVisualStyleBackColor = true;
            this.tpConsorcistas.Name = "tpConsorcistas";
            this.tpConsorcistas.TabIndex = 2;
            this.tlpConsorcios.Controls.Add(this.dgvConsorcios, 0, 0);
            this.tlpConsorcios.Controls.Add(this.pnlDetalleConsorcio, 1, 0);
            this.tlpConsorcios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.tlpConsorcios.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tlpConsorcios.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpConsorcios.ColumnCount = 2;
            this.tlpConsorcios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpConsorcios.RowCount = 1;
            this.tlpConsorcios.Padding = new System.Windows.Forms.Padding(3);
            this.tlpConsorcios.Name = "tlpConsorcios";
            this.tlpConsorcios.TabIndex = 0;
            this.dgvConsorcios.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvConsorciosColId, this.dgvConsorciosColNombre, this.dgvConsorciosColDireccion, this.dgvConsorciosColCantidadUnidades, this.dgvConsorciosColActivo});
            this.dgvConsorcios.AllowUserToAddRows = false;
            this.dgvConsorcios.AllowUserToDeleteRows = false;
            this.dgvConsorcios.AllowUserToResizeRows = false;
            this.dgvConsorcios.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvConsorcios.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvConsorcios.MultiSelect = false;
            this.dgvConsorcios.ReadOnly = true;
            this.dgvConsorcios.RowHeadersVisible = false;
            this.dgvConsorcios.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvConsorcios.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvConsorcios.Size = new System.Drawing.Size(660, 600);
            this.dgvConsorcios.Name = "dgvConsorcios";
            this.dgvConsorcios.TabIndex = 0;
            this.dgvConsorcios.SelectionChanged += new System.EventHandler(this.dgvConsorcios_SelectionChanged_413BE);
            this.dgvConsorciosColId.HeaderText = "Id";
            this.dgvConsorciosColId.Tag = "col_man_dgvConsorciosColId";
            this.dgvConsorciosColId.Name = "dgvConsorciosColId";
            this.dgvConsorciosColId.ReadOnly = true;
            this.dgvConsorciosColId.FillWeight = 20F;
            this.dgvConsorciosColNombre.HeaderText = "Nombre";
            this.dgvConsorciosColNombre.Tag = "col_man_dgvConsorciosColNombre";
            this.dgvConsorciosColNombre.Name = "dgvConsorciosColNombre";
            this.dgvConsorciosColNombre.ReadOnly = true;
            this.dgvConsorciosColNombre.FillWeight = 40F;
            this.dgvConsorciosColDireccion.HeaderText = "Dirección";
            this.dgvConsorciosColDireccion.Tag = "col_man_dgvConsorciosColDireccion";
            this.dgvConsorciosColDireccion.Name = "dgvConsorciosColDireccion";
            this.dgvConsorciosColDireccion.ReadOnly = true;
            this.dgvConsorciosColDireccion.FillWeight = 40F;
            this.dgvConsorciosColCantidadUnidades.HeaderText = "Cantidad de unidades";
            this.dgvConsorciosColCantidadUnidades.Tag = "col_man_dgvConsorciosColCantidadUnidades";
            this.dgvConsorciosColCantidadUnidades.Name = "dgvConsorciosColCantidadUnidades";
            this.dgvConsorciosColCantidadUnidades.ReadOnly = true;
            this.dgvConsorciosColCantidadUnidades.FillWeight = 30F;
            this.dgvConsorciosColActivo.HeaderText = "Activo";
            this.dgvConsorciosColActivo.Tag = "col_man_dgvConsorciosColActivo";
            this.dgvConsorciosColActivo.Name = "dgvConsorciosColActivo";
            this.dgvConsorciosColActivo.ReadOnly = true;
            this.dgvConsorciosColActivo.FillWeight = 20F;
            this.pnlDetalleConsorcio.Controls.Add(this.lblNombre);
            this.pnlDetalleConsorcio.Controls.Add(this.txtNombre);
            this.pnlDetalleConsorcio.Controls.Add(this.lblDireccion);
            this.pnlDetalleConsorcio.Controls.Add(this.txtDireccion);
            this.pnlDetalleConsorcio.Controls.Add(this.lblCantidadUnidades);
            this.pnlDetalleConsorcio.Controls.Add(this.numCantidadUnidades);
            this.pnlDetalleConsorcio.Controls.Add(this.chkActivo);
            this.pnlDetalleConsorcio.Controls.Add(this.btnNuevoConsorcio);
            this.pnlDetalleConsorcio.Controls.Add(this.btnGuardarConsorcio);
            this.pnlDetalleConsorcio.Controls.Add(this.btnInactivarConsorcio);
            this.pnlDetalleConsorcio.Controls.Add(this.btnReactivarConsorcio);
            this.pnlDetalleConsorcio.Controls.Add(this.btnCancelarConsorcio);
            this.pnlDetalleConsorcio.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDetalleConsorcio.Name = "pnlDetalleConsorcio";
            this.pnlDetalleConsorcio.TabIndex = 1;
            this.lblNombre.AutoSize = true;
            this.lblNombre.Location = new System.Drawing.Point(0, 3);
            this.lblNombre.Text = "Nombre";
            this.lblNombre.Tag = "lb_man_lblNombre";
            this.lblNombre.Name = "lblNombre";
            this.lblNombre.TabIndex = 0;
            this.txtNombre.Location = new System.Drawing.Point(0, 22);
            this.txtNombre.Size = new System.Drawing.Size(300, 23);
            this.txtNombre.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtNombre.Name = "txtNombre";
            this.txtNombre.TabIndex = 1;
            this.txtNombre.TextChanged += new System.EventHandler(this.txtNombre_TextChanged_413BE);
            this.lblDireccion.AutoSize = true;
            this.lblDireccion.Location = new System.Drawing.Point(0, 58);
            this.lblDireccion.Text = "Dirección";
            this.lblDireccion.Tag = "lb_man_lblDireccion";
            this.lblDireccion.Name = "lblDireccion";
            this.lblDireccion.TabIndex = 2;
            this.txtDireccion.Location = new System.Drawing.Point(0, 77);
            this.txtDireccion.Size = new System.Drawing.Size(300, 23);
            this.txtDireccion.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtDireccion.Name = "txtDireccion";
            this.txtDireccion.TabIndex = 3;
            this.txtDireccion.TextChanged += new System.EventHandler(this.txtDireccion_TextChanged_413BE);
            this.lblCantidadUnidades.AutoSize = true;
            this.lblCantidadUnidades.Location = new System.Drawing.Point(0, 113);
            this.lblCantidadUnidades.Text = "Cantidad de unidades";
            this.lblCantidadUnidades.Tag = "lb_man_lblCantidadUnidades";
            this.lblCantidadUnidades.Name = "lblCantidadUnidades";
            this.lblCantidadUnidades.TabIndex = 4;
            this.numCantidadUnidades.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.numCantidadUnidades.Location = new System.Drawing.Point(0, 132);
            this.numCantidadUnidades.Maximum = new decimal(new int[] { 9999, 0, 0, 0});
            this.numCantidadUnidades.Minimum = new decimal(new int[] { 1, 0, 0, 0});
            this.numCantidadUnidades.Size = new System.Drawing.Size(120, 23);
            this.numCantidadUnidades.Value = new decimal(new int[] { 1, 0, 0, 0});
            this.numCantidadUnidades.Name = "numCantidadUnidades";
            this.numCantidadUnidades.TabIndex = 5;
            this.numCantidadUnidades.ValueChanged += new System.EventHandler(this.numCantidadUnidades_ValueChanged_413BE);
            this.chkActivo.AutoSize = true;
            this.chkActivo.Location = new System.Drawing.Point(0, 168);
            this.chkActivo.Text = "Activo";
            this.chkActivo.Tag = "chk_man_chkActivo";
            this.chkActivo.UseVisualStyleBackColor = true;
            this.chkActivo.Enabled = false;
            this.chkActivo.Name = "chkActivo";
            this.chkActivo.TabIndex = 6;
            this.btnNuevoConsorcio.Location = new System.Drawing.Point(0, 200);
            this.btnNuevoConsorcio.Size = new System.Drawing.Size(100, 27);
            this.btnNuevoConsorcio.Text = "Nuevo";
            this.btnNuevoConsorcio.Tag = "btn_man_btnNuevoConsorcio";
            this.btnNuevoConsorcio.UseVisualStyleBackColor = true;
            this.btnNuevoConsorcio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnNuevoConsorcio.Name = "btnNuevoConsorcio";
            this.btnNuevoConsorcio.TabIndex = 7;
            this.btnNuevoConsorcio.Click += new System.EventHandler(this.btnNuevoConsorcio_Click_413BE);
            this.btnGuardarConsorcio.Location = new System.Drawing.Point(0, 234);
            this.btnGuardarConsorcio.Size = new System.Drawing.Size(100, 27);
            this.btnGuardarConsorcio.Text = "Guardar";
            this.btnGuardarConsorcio.Tag = "btn_man_btnGuardarConsorcio";
            this.btnGuardarConsorcio.UseVisualStyleBackColor = true;
            this.btnGuardarConsorcio.Enabled = false;
            this.btnGuardarConsorcio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnGuardarConsorcio.Name = "btnGuardarConsorcio";
            this.btnGuardarConsorcio.TabIndex = 8;
            this.btnGuardarConsorcio.Click += new System.EventHandler(this.btnGuardarConsorcio_Click_413BE);
            this.btnInactivarConsorcio.Location = new System.Drawing.Point(0, 268);
            this.btnInactivarConsorcio.Size = new System.Drawing.Size(100, 27);
            this.btnInactivarConsorcio.Text = "Inactivar";
            this.btnInactivarConsorcio.Tag = "btn_man_btnInactivarConsorcio";
            this.btnInactivarConsorcio.UseVisualStyleBackColor = true;
            this.btnInactivarConsorcio.Enabled = false;
            this.btnInactivarConsorcio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnInactivarConsorcio.Name = "btnInactivarConsorcio";
            this.btnInactivarConsorcio.TabIndex = 9;
            this.btnInactivarConsorcio.Click += new System.EventHandler(this.btnInactivarConsorcio_Click_413BE);
            this.btnReactivarConsorcio.Location = new System.Drawing.Point(110, 268);
            this.btnReactivarConsorcio.Size = new System.Drawing.Size(100, 27);
            this.btnReactivarConsorcio.Text = "Reactivar";
            this.btnReactivarConsorcio.Tag = "btn_man_btnReactivarConsorcio";
            this.btnReactivarConsorcio.UseVisualStyleBackColor = true;
            this.btnReactivarConsorcio.Enabled = false;
            this.btnReactivarConsorcio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnReactivarConsorcio.Name = "btnReactivarConsorcio";
            this.btnReactivarConsorcio.TabIndex = 10;
            this.btnReactivarConsorcio.Click += new System.EventHandler(this.btnReactivarConsorcio_Click_413BE);
            this.btnCancelarConsorcio.Location = new System.Drawing.Point(0, 302);
            this.btnCancelarConsorcio.Size = new System.Drawing.Size(100, 27);
            this.btnCancelarConsorcio.Text = "Cancelar";
            this.btnCancelarConsorcio.Tag = "btn_man_btnCancelarConsorcio";
            this.btnCancelarConsorcio.UseVisualStyleBackColor = true;
            this.btnCancelarConsorcio.Enabled = false;
            this.btnCancelarConsorcio.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnCancelarConsorcio.Name = "btnCancelarConsorcio";
            this.btnCancelarConsorcio.TabIndex = 11;
            this.btnCancelarConsorcio.Click += new System.EventHandler(this.btnCancelarConsorcio_Click_413BE);
            this.tlpUnidadesFuncionales.Controls.Add(this.pnlListaUnidadesFuncionales, 0, 0);
            this.tlpUnidadesFuncionales.Controls.Add(this.pnlDetalleUnidadFuncional, 1, 0);
            this.tlpUnidadesFuncionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.tlpUnidadesFuncionales.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tlpUnidadesFuncionales.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpUnidadesFuncionales.ColumnCount = 2;
            this.tlpUnidadesFuncionales.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpUnidadesFuncionales.RowCount = 1;
            this.tlpUnidadesFuncionales.Padding = new System.Windows.Forms.Padding(3);
            this.tlpUnidadesFuncionales.Name = "tlpUnidadesFuncionales";
            this.tlpUnidadesFuncionales.TabIndex = 0;
            this.pnlListaUnidadesFuncionales.Controls.Add(this.dgvUnidadesFuncionales);
            this.pnlListaUnidadesFuncionales.Controls.Add(this.pnlFiltroConsorcioUF);
            this.pnlListaUnidadesFuncionales.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlListaUnidadesFuncionales.Name = "pnlListaUnidadesFuncionales";
            this.pnlListaUnidadesFuncionales.TabIndex = 0;
            this.dgvUnidadesFuncionales.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvUnidadesFuncionalesColId, this.dgvUnidadesFuncionalesColIdentificador, this.dgvUnidadesFuncionalesColTipo, this.dgvUnidadesFuncionalesColActiva});
            this.dgvUnidadesFuncionales.AllowUserToAddRows = false;
            this.dgvUnidadesFuncionales.AllowUserToDeleteRows = false;
            this.dgvUnidadesFuncionales.AllowUserToResizeRows = false;
            this.dgvUnidadesFuncionales.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvUnidadesFuncionales.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvUnidadesFuncionales.MultiSelect = false;
            this.dgvUnidadesFuncionales.ReadOnly = true;
            this.dgvUnidadesFuncionales.RowHeadersVisible = false;
            this.dgvUnidadesFuncionales.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvUnidadesFuncionales.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvUnidadesFuncionales.Size = new System.Drawing.Size(660, 560);
            this.dgvUnidadesFuncionales.Name = "dgvUnidadesFuncionales";
            this.dgvUnidadesFuncionales.TabIndex = 0;
            this.dgvUnidadesFuncionales.SelectionChanged += new System.EventHandler(this.dgvUnidadesFuncionales_SelectionChanged_413BE);
            this.dgvUnidadesFuncionalesColId.HeaderText = "Id";
            this.dgvUnidadesFuncionalesColId.Tag = "col_man_dgvUnidadesFuncionalesColId";
            this.dgvUnidadesFuncionalesColId.Name = "dgvUnidadesFuncionalesColId";
            this.dgvUnidadesFuncionalesColId.ReadOnly = true;
            this.dgvUnidadesFuncionalesColId.FillWeight = 20F;
            this.dgvUnidadesFuncionalesColIdentificador.HeaderText = "Identificador";
            this.dgvUnidadesFuncionalesColIdentificador.Tag = "col_man_dgvUnidadesFuncionalesColIdentificador";
            this.dgvUnidadesFuncionalesColIdentificador.Name = "dgvUnidadesFuncionalesColIdentificador";
            this.dgvUnidadesFuncionalesColIdentificador.ReadOnly = true;
            this.dgvUnidadesFuncionalesColIdentificador.FillWeight = 35F;
            this.dgvUnidadesFuncionalesColTipo.HeaderText = "Tipo";
            this.dgvUnidadesFuncionalesColTipo.Tag = "col_man_dgvUnidadesFuncionalesColTipo";
            this.dgvUnidadesFuncionalesColTipo.Name = "dgvUnidadesFuncionalesColTipo";
            this.dgvUnidadesFuncionalesColTipo.ReadOnly = true;
            this.dgvUnidadesFuncionalesColTipo.FillWeight = 25F;
            this.dgvUnidadesFuncionalesColActiva.HeaderText = "Activa";
            this.dgvUnidadesFuncionalesColActiva.Tag = "col_man_dgvUnidadesFuncionalesColActiva";
            this.dgvUnidadesFuncionalesColActiva.Name = "dgvUnidadesFuncionalesColActiva";
            this.dgvUnidadesFuncionalesColActiva.ReadOnly = true;
            this.dgvUnidadesFuncionalesColActiva.FillWeight = 20F;
            this.pnlFiltroConsorcioUF.Controls.Add(this.lblConsorcio);
            this.pnlFiltroConsorcioUF.Controls.Add(this.cboConsorcio);
            this.pnlFiltroConsorcioUF.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlFiltroConsorcioUF.Size = new System.Drawing.Size(660, 36);
            this.pnlFiltroConsorcioUF.Name = "pnlFiltroConsorcioUF";
            this.pnlFiltroConsorcioUF.TabIndex = 1;
            this.lblConsorcio.AutoSize = true;
            this.lblConsorcio.Location = new System.Drawing.Point(0, 9);
            this.lblConsorcio.Text = "Consorcio";
            this.lblConsorcio.Tag = "lb_man_lblConsorcio";
            this.lblConsorcio.Name = "lblConsorcio";
            this.lblConsorcio.TabIndex = 0;
            this.cboConsorcio.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConsorcio.FormattingEnabled = true;
            this.cboConsorcio.Location = new System.Drawing.Point(90, 5);
            this.cboConsorcio.Size = new System.Drawing.Size(300, 23);
            this.cboConsorcio.Name = "cboConsorcio";
            this.cboConsorcio.TabIndex = 1;
            this.cboConsorcio.SelectedIndexChanged += new System.EventHandler(this.cboConsorcio_SelectedIndexChanged_413BE);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.lblIdentificador);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.txtIdentificador);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.lblTipo);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.cboTipo);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.chkActiva);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.btnNuevoUnidadFuncional);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.btnGuardarUnidadFuncional);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.btnInactivarUnidadFuncional);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.btnReactivarUnidadFuncional);
            this.pnlDetalleUnidadFuncional.Controls.Add(this.btnCancelarUnidadFuncional);
            this.pnlDetalleUnidadFuncional.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDetalleUnidadFuncional.Name = "pnlDetalleUnidadFuncional";
            this.pnlDetalleUnidadFuncional.TabIndex = 1;
            this.lblIdentificador.AutoSize = true;
            this.lblIdentificador.Location = new System.Drawing.Point(0, 3);
            this.lblIdentificador.Text = "Identificador";
            this.lblIdentificador.Tag = "lb_man_lblIdentificador";
            this.lblIdentificador.Name = "lblIdentificador";
            this.lblIdentificador.TabIndex = 0;
            this.txtIdentificador.Location = new System.Drawing.Point(0, 22);
            this.txtIdentificador.Size = new System.Drawing.Size(300, 23);
            this.txtIdentificador.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtIdentificador.Name = "txtIdentificador";
            this.txtIdentificador.TabIndex = 1;
            this.txtIdentificador.TextChanged += new System.EventHandler(this.txtIdentificador_TextChanged_413BE);
            this.lblTipo.AutoSize = true;
            this.lblTipo.Location = new System.Drawing.Point(0, 58);
            this.lblTipo.Text = "Tipo";
            this.lblTipo.Tag = "lb_man_lblTipo";
            this.lblTipo.Name = "lblTipo";
            this.lblTipo.TabIndex = 2;
            this.cboTipo.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboTipo.FormattingEnabled = true;
            this.cboTipo.Location = new System.Drawing.Point(0, 77);
            this.cboTipo.Size = new System.Drawing.Size(200, 23);
            this.cboTipo.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.cboTipo.Name = "cboTipo";
            this.cboTipo.TabIndex = 3;
            this.cboTipo.SelectedIndexChanged += new System.EventHandler(this.cboTipo_SelectedIndexChanged_413BE);
            this.chkActiva.AutoSize = true;
            this.chkActiva.Location = new System.Drawing.Point(0, 113);
            this.chkActiva.Text = "Activa";
            this.chkActiva.Tag = "chk_man_chkActiva";
            this.chkActiva.UseVisualStyleBackColor = true;
            this.chkActiva.Enabled = false;
            this.chkActiva.Name = "chkActiva";
            this.chkActiva.TabIndex = 4;
            this.btnNuevoUnidadFuncional.Location = new System.Drawing.Point(0, 145);
            this.btnNuevoUnidadFuncional.Size = new System.Drawing.Size(100, 27);
            this.btnNuevoUnidadFuncional.Text = "Nuevo";
            this.btnNuevoUnidadFuncional.Tag = "btn_man_btnNuevoUnidadFuncional";
            this.btnNuevoUnidadFuncional.UseVisualStyleBackColor = true;
            this.btnNuevoUnidadFuncional.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnNuevoUnidadFuncional.Name = "btnNuevoUnidadFuncional";
            this.btnNuevoUnidadFuncional.TabIndex = 5;
            this.btnNuevoUnidadFuncional.Click += new System.EventHandler(this.btnNuevoUnidadFuncional_Click_413BE);
            this.btnGuardarUnidadFuncional.Location = new System.Drawing.Point(0, 179);
            this.btnGuardarUnidadFuncional.Size = new System.Drawing.Size(100, 27);
            this.btnGuardarUnidadFuncional.Text = "Guardar";
            this.btnGuardarUnidadFuncional.Tag = "btn_man_btnGuardarUnidadFuncional";
            this.btnGuardarUnidadFuncional.UseVisualStyleBackColor = true;
            this.btnGuardarUnidadFuncional.Enabled = false;
            this.btnGuardarUnidadFuncional.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnGuardarUnidadFuncional.Name = "btnGuardarUnidadFuncional";
            this.btnGuardarUnidadFuncional.TabIndex = 6;
            this.btnGuardarUnidadFuncional.Click += new System.EventHandler(this.btnGuardarUnidadFuncional_Click_413BE);
            this.btnInactivarUnidadFuncional.Location = new System.Drawing.Point(0, 213);
            this.btnInactivarUnidadFuncional.Size = new System.Drawing.Size(100, 27);
            this.btnInactivarUnidadFuncional.Text = "Inactivar";
            this.btnInactivarUnidadFuncional.Tag = "btn_man_btnInactivarUnidadFuncional";
            this.btnInactivarUnidadFuncional.UseVisualStyleBackColor = true;
            this.btnInactivarUnidadFuncional.Enabled = false;
            this.btnInactivarUnidadFuncional.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnInactivarUnidadFuncional.Name = "btnInactivarUnidadFuncional";
            this.btnInactivarUnidadFuncional.TabIndex = 7;
            this.btnInactivarUnidadFuncional.Click += new System.EventHandler(this.btnInactivarUnidadFuncional_Click_413BE);
            this.btnReactivarUnidadFuncional.Location = new System.Drawing.Point(110, 213);
            this.btnReactivarUnidadFuncional.Size = new System.Drawing.Size(100, 27);
            this.btnReactivarUnidadFuncional.Text = "Reactivar";
            this.btnReactivarUnidadFuncional.Tag = "btn_man_btnReactivarUnidadFuncional";
            this.btnReactivarUnidadFuncional.UseVisualStyleBackColor = true;
            this.btnReactivarUnidadFuncional.Enabled = false;
            this.btnReactivarUnidadFuncional.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnReactivarUnidadFuncional.Name = "btnReactivarUnidadFuncional";
            this.btnReactivarUnidadFuncional.TabIndex = 8;
            this.btnReactivarUnidadFuncional.Click += new System.EventHandler(this.btnReactivarUnidadFuncional_Click_413BE);
            this.btnCancelarUnidadFuncional.Location = new System.Drawing.Point(0, 247);
            this.btnCancelarUnidadFuncional.Size = new System.Drawing.Size(100, 27);
            this.btnCancelarUnidadFuncional.Text = "Cancelar";
            this.btnCancelarUnidadFuncional.Tag = "btn_man_btnCancelarUnidadFuncional";
            this.btnCancelarUnidadFuncional.UseVisualStyleBackColor = true;
            this.btnCancelarUnidadFuncional.Enabled = false;
            this.btnCancelarUnidadFuncional.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnCancelarUnidadFuncional.Name = "btnCancelarUnidadFuncional";
            this.btnCancelarUnidadFuncional.TabIndex = 9;
            this.btnCancelarUnidadFuncional.Click += new System.EventHandler(this.btnCancelarUnidadFuncional_Click_413BE);
            this.tlpConsorcistas.Controls.Add(this.pnlListaConsorcistas, 0, 0);
            this.tlpConsorcistas.Controls.Add(this.pnlDetalleConsorcista, 1, 0);
            this.tlpConsorcistas.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 65F));
            this.tlpConsorcistas.ColumnStyles.Add(new System.Windows.Forms.ColumnStyle(System.Windows.Forms.SizeType.Percent, 35F));
            this.tlpConsorcistas.RowStyles.Add(new System.Windows.Forms.RowStyle(System.Windows.Forms.SizeType.Percent, 100F));
            this.tlpConsorcistas.ColumnCount = 2;
            this.tlpConsorcistas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.tlpConsorcistas.RowCount = 1;
            this.tlpConsorcistas.Padding = new System.Windows.Forms.Padding(3);
            this.tlpConsorcistas.Name = "tlpConsorcistas";
            this.tlpConsorcistas.TabIndex = 0;
            this.pnlListaConsorcistas.Controls.Add(this.dgvConsorcistas);
            this.pnlListaConsorcistas.Controls.Add(this.pnlFiltroConsorcista);
            this.pnlListaConsorcistas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlListaConsorcistas.Name = "pnlListaConsorcistas";
            this.pnlListaConsorcistas.TabIndex = 0;
            this.dgvConsorcistas.Columns.AddRange(new System.Windows.Forms.DataGridViewColumn[] {
            this.dgvConsorcistasColId, this.dgvConsorcistasColDni, this.dgvConsorcistasColNombre, this.dgvConsorcistasColEmail, this.dgvConsorcistasColTipo, this.dgvConsorcistasColActivo});
            this.dgvConsorcistas.AllowUserToAddRows = false;
            this.dgvConsorcistas.AllowUserToDeleteRows = false;
            this.dgvConsorcistas.AllowUserToResizeRows = false;
            this.dgvConsorcistas.AutoSizeColumnsMode = System.Windows.Forms.DataGridViewAutoSizeColumnsMode.Fill;
            this.dgvConsorcistas.ColumnHeadersHeightSizeMode = System.Windows.Forms.DataGridViewColumnHeadersHeightSizeMode.AutoSize;
            this.dgvConsorcistas.MultiSelect = false;
            this.dgvConsorcistas.ReadOnly = true;
            this.dgvConsorcistas.RowHeadersVisible = false;
            this.dgvConsorcistas.SelectionMode = System.Windows.Forms.DataGridViewSelectionMode.FullRowSelect;
            this.dgvConsorcistas.Dock = System.Windows.Forms.DockStyle.Fill;
            this.dgvConsorcistas.Size = new System.Drawing.Size(660, 520);
            this.dgvConsorcistas.Name = "dgvConsorcistas";
            this.dgvConsorcistas.TabIndex = 0;
            this.dgvConsorcistas.SelectionChanged += new System.EventHandler(this.dgvConsorcistas_SelectionChanged_413BE);
            this.dgvConsorcistasColId.HeaderText = "Id";
            this.dgvConsorcistasColId.Tag = "col_man_dgvConsorcistasColId";
            this.dgvConsorcistasColId.Name = "dgvConsorcistasColId";
            this.dgvConsorcistasColId.ReadOnly = true;
            this.dgvConsorcistasColId.FillWeight = 12F;
            this.dgvConsorcistasColDni.HeaderText = "DNI";
            this.dgvConsorcistasColDni.Tag = "col_man_dgvConsorcistasColDni";
            this.dgvConsorcistasColDni.Name = "dgvConsorcistasColDni";
            this.dgvConsorcistasColDni.ReadOnly = true;
            this.dgvConsorcistasColDni.FillWeight = 18F;
            this.dgvConsorcistasColNombre.HeaderText = "Nombre";
            this.dgvConsorcistasColNombre.Tag = "col_man_dgvConsorcistasColNombre";
            this.dgvConsorcistasColNombre.Name = "dgvConsorcistasColNombre";
            this.dgvConsorcistasColNombre.ReadOnly = true;
            this.dgvConsorcistasColNombre.FillWeight = 25F;
            this.dgvConsorcistasColEmail.HeaderText = "Email";
            this.dgvConsorcistasColEmail.Tag = "col_man_dgvConsorcistasColEmail";
            this.dgvConsorcistasColEmail.Name = "dgvConsorcistasColEmail";
            this.dgvConsorcistasColEmail.ReadOnly = true;
            this.dgvConsorcistasColEmail.FillWeight = 25F;
            this.dgvConsorcistasColTipo.HeaderText = "Propietario/Inquilino";
            this.dgvConsorcistasColTipo.Tag = "col_man_dgvConsorcistasColTipo";
            this.dgvConsorcistasColTipo.Name = "dgvConsorcistasColTipo";
            this.dgvConsorcistasColTipo.ReadOnly = true;
            this.dgvConsorcistasColTipo.FillWeight = 20F;
            this.dgvConsorcistasColActivo.HeaderText = "Activo";
            this.dgvConsorcistasColActivo.Tag = "col_man_dgvConsorcistasColActivo";
            this.dgvConsorcistasColActivo.Name = "dgvConsorcistasColActivo";
            this.dgvConsorcistasColActivo.ReadOnly = true;
            this.dgvConsorcistasColActivo.FillWeight = 12F;
            this.pnlFiltroConsorcista.Controls.Add(this.lblConsorcioConsorcista);
            this.pnlFiltroConsorcista.Controls.Add(this.cboConsorcioConsorcista);
            this.pnlFiltroConsorcista.Controls.Add(this.lblUnidadFuncionalConsorcista);
            this.pnlFiltroConsorcista.Controls.Add(this.cboUnidadFuncionalConsorcista);
            this.pnlFiltroConsorcista.Dock = System.Windows.Forms.DockStyle.Top;
            this.pnlFiltroConsorcista.Size = new System.Drawing.Size(660, 72);
            this.pnlFiltroConsorcista.Name = "pnlFiltroConsorcista";
            this.pnlFiltroConsorcista.TabIndex = 1;
            this.lblConsorcioConsorcista.AutoSize = true;
            this.lblConsorcioConsorcista.Location = new System.Drawing.Point(0, 9);
            this.lblConsorcioConsorcista.Text = "Consorcio";
            this.lblConsorcioConsorcista.Tag = "lb_man_lblConsorcioConsorcista";
            this.lblConsorcioConsorcista.Name = "lblConsorcioConsorcista";
            this.lblConsorcioConsorcista.TabIndex = 0;
            this.cboConsorcioConsorcista.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboConsorcioConsorcista.FormattingEnabled = true;
            this.cboConsorcioConsorcista.Location = new System.Drawing.Point(140, 5);
            this.cboConsorcioConsorcista.Size = new System.Drawing.Size(300, 23);
            this.cboConsorcioConsorcista.Name = "cboConsorcioConsorcista";
            this.cboConsorcioConsorcista.TabIndex = 1;
            this.cboConsorcioConsorcista.SelectedIndexChanged += new System.EventHandler(this.cboConsorcioConsorcista_SelectedIndexChanged_413BE);
            this.lblUnidadFuncionalConsorcista.AutoSize = true;
            this.lblUnidadFuncionalConsorcista.Location = new System.Drawing.Point(0, 43);
            this.lblUnidadFuncionalConsorcista.Text = "Unidad funcional";
            this.lblUnidadFuncionalConsorcista.Tag = "lb_man_lblUnidadFuncionalConsorcista";
            this.lblUnidadFuncionalConsorcista.Name = "lblUnidadFuncionalConsorcista";
            this.lblUnidadFuncionalConsorcista.TabIndex = 2;
            this.cboUnidadFuncionalConsorcista.DropDownStyle = System.Windows.Forms.ComboBoxStyle.DropDownList;
            this.cboUnidadFuncionalConsorcista.FormattingEnabled = true;
            this.cboUnidadFuncionalConsorcista.Location = new System.Drawing.Point(140, 39);
            this.cboUnidadFuncionalConsorcista.Size = new System.Drawing.Size(300, 23);
            this.cboUnidadFuncionalConsorcista.Name = "cboUnidadFuncionalConsorcista";
            this.cboUnidadFuncionalConsorcista.TabIndex = 3;
            this.cboUnidadFuncionalConsorcista.SelectedIndexChanged += new System.EventHandler(this.cboUnidadFuncionalConsorcista_SelectedIndexChanged_413BE);
            this.pnlDetalleConsorcista.Controls.Add(this.lblDni);
            this.pnlDetalleConsorcista.Controls.Add(this.txtDni);
            this.pnlDetalleConsorcista.Controls.Add(this.lblNombreConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.txtNombreConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.lblEmailConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.txtEmailConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.rdoPropietario);
            this.pnlDetalleConsorcista.Controls.Add(this.rdoInquilino);
            this.pnlDetalleConsorcista.Controls.Add(this.chkActivoConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.btnNuevoConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.btnGuardarConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.btnInactivarConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.btnReactivarConsorcista);
            this.pnlDetalleConsorcista.Controls.Add(this.btnCancelarConsorcista);
            this.pnlDetalleConsorcista.Dock = System.Windows.Forms.DockStyle.Fill;
            this.pnlDetalleConsorcista.Name = "pnlDetalleConsorcista";
            this.pnlDetalleConsorcista.TabIndex = 1;
            this.lblDni.AutoSize = true;
            this.lblDni.Location = new System.Drawing.Point(0, 3);
            this.lblDni.Text = "DNI";
            this.lblDni.Tag = "lb_man_lblDni";
            this.lblDni.Name = "lblDni";
            this.lblDni.TabIndex = 0;
            this.txtDni.Location = new System.Drawing.Point(0, 22);
            this.txtDni.Size = new System.Drawing.Size(200, 23);
            this.txtDni.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtDni.Name = "txtDni";
            this.txtDni.TabIndex = 1;
            this.txtDni.TextChanged += new System.EventHandler(this.txtDni_TextChanged_413BE);
            this.lblNombreConsorcista.AutoSize = true;
            this.lblNombreConsorcista.Location = new System.Drawing.Point(0, 58);
            this.lblNombreConsorcista.Text = "Nombre";
            this.lblNombreConsorcista.Tag = "lb_man_lblNombreConsorcista";
            this.lblNombreConsorcista.Name = "lblNombreConsorcista";
            this.lblNombreConsorcista.TabIndex = 2;
            this.txtNombreConsorcista.Location = new System.Drawing.Point(0, 77);
            this.txtNombreConsorcista.Size = new System.Drawing.Size(300, 23);
            this.txtNombreConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtNombreConsorcista.Name = "txtNombreConsorcista";
            this.txtNombreConsorcista.TabIndex = 3;
            this.txtNombreConsorcista.TextChanged += new System.EventHandler(this.txtNombreConsorcista_TextChanged_413BE);
            this.lblEmailConsorcista.AutoSize = true;
            this.lblEmailConsorcista.Location = new System.Drawing.Point(0, 113);
            this.lblEmailConsorcista.Text = "Email";
            this.lblEmailConsorcista.Tag = "lb_man_lblEmailConsorcista";
            this.lblEmailConsorcista.Name = "lblEmailConsorcista";
            this.lblEmailConsorcista.TabIndex = 4;
            this.txtEmailConsorcista.Location = new System.Drawing.Point(0, 132);
            this.txtEmailConsorcista.Size = new System.Drawing.Size(300, 23);
            this.txtEmailConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.txtEmailConsorcista.Name = "txtEmailConsorcista";
            this.txtEmailConsorcista.TabIndex = 5;
            this.txtEmailConsorcista.TextChanged += new System.EventHandler(this.txtEmailConsorcista_TextChanged_413BE);
            this.rdoPropietario.AutoSize = true;
            this.rdoPropietario.Location = new System.Drawing.Point(0, 168);
            this.rdoPropietario.Text = "Propietario";
            this.rdoPropietario.Tag = "rdo_man_rdoPropietario";
            this.rdoPropietario.UseVisualStyleBackColor = true;
            this.rdoPropietario.Checked = true;
            this.rdoPropietario.Name = "rdoPropietario";
            this.rdoPropietario.TabIndex = 6;
            this.rdoPropietario.CheckedChanged += new System.EventHandler(this.rdoPropietario_CheckedChanged_413BE);
            this.rdoInquilino.AutoSize = true;
            this.rdoInquilino.Location = new System.Drawing.Point(130, 168);
            this.rdoInquilino.Text = "Inquilino";
            this.rdoInquilino.Tag = "rdo_man_rdoInquilino";
            this.rdoInquilino.UseVisualStyleBackColor = true;
            this.rdoInquilino.Name = "rdoInquilino";
            this.rdoInquilino.TabIndex = 7;
            this.chkActivoConsorcista.AutoSize = true;
            this.chkActivoConsorcista.Location = new System.Drawing.Point(0, 196);
            this.chkActivoConsorcista.Text = "Activo";
            this.chkActivoConsorcista.Tag = "chk_man_chkActivoConsorcista";
            this.chkActivoConsorcista.UseVisualStyleBackColor = true;
            this.chkActivoConsorcista.Enabled = false;
            this.chkActivoConsorcista.Name = "chkActivoConsorcista";
            this.chkActivoConsorcista.TabIndex = 8;
            this.btnNuevoConsorcista.Location = new System.Drawing.Point(0, 228);
            this.btnNuevoConsorcista.Size = new System.Drawing.Size(100, 27);
            this.btnNuevoConsorcista.Text = "Nuevo";
            this.btnNuevoConsorcista.Tag = "btn_man_btnNuevoConsorcista";
            this.btnNuevoConsorcista.UseVisualStyleBackColor = true;
            this.btnNuevoConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnNuevoConsorcista.Name = "btnNuevoConsorcista";
            this.btnNuevoConsorcista.TabIndex = 9;
            this.btnNuevoConsorcista.Click += new System.EventHandler(this.btnNuevoConsorcista_Click_413BE);
            this.btnGuardarConsorcista.Location = new System.Drawing.Point(0, 262);
            this.btnGuardarConsorcista.Size = new System.Drawing.Size(100, 27);
            this.btnGuardarConsorcista.Text = "Guardar";
            this.btnGuardarConsorcista.Tag = "btn_man_btnGuardarConsorcista";
            this.btnGuardarConsorcista.UseVisualStyleBackColor = true;
            this.btnGuardarConsorcista.Enabled = false;
            this.btnGuardarConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnGuardarConsorcista.Name = "btnGuardarConsorcista";
            this.btnGuardarConsorcista.TabIndex = 10;
            this.btnGuardarConsorcista.Click += new System.EventHandler(this.btnGuardarConsorcista_Click_413BE);
            this.btnInactivarConsorcista.Location = new System.Drawing.Point(0, 296);
            this.btnInactivarConsorcista.Size = new System.Drawing.Size(100, 27);
            this.btnInactivarConsorcista.Text = "Inactivar";
            this.btnInactivarConsorcista.Tag = "btn_man_btnInactivarConsorcista";
            this.btnInactivarConsorcista.UseVisualStyleBackColor = true;
            this.btnInactivarConsorcista.Enabled = false;
            this.btnInactivarConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnInactivarConsorcista.Name = "btnInactivarConsorcista";
            this.btnInactivarConsorcista.TabIndex = 11;
            this.btnInactivarConsorcista.Click += new System.EventHandler(this.btnInactivarConsorcista_Click_413BE);
            this.btnReactivarConsorcista.Location = new System.Drawing.Point(110, 296);
            this.btnReactivarConsorcista.Size = new System.Drawing.Size(100, 27);
            this.btnReactivarConsorcista.Text = "Reactivar";
            this.btnReactivarConsorcista.Tag = "btn_man_btnReactivarConsorcista";
            this.btnReactivarConsorcista.UseVisualStyleBackColor = true;
            this.btnReactivarConsorcista.Enabled = false;
            this.btnReactivarConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnReactivarConsorcista.Name = "btnReactivarConsorcista";
            this.btnReactivarConsorcista.TabIndex = 12;
            this.btnReactivarConsorcista.Click += new System.EventHandler(this.btnReactivarConsorcista_Click_413BE);
            this.btnCancelarConsorcista.Location = new System.Drawing.Point(0, 330);
            this.btnCancelarConsorcista.Size = new System.Drawing.Size(100, 27);
            this.btnCancelarConsorcista.Text = "Cancelar";
            this.btnCancelarConsorcista.Tag = "btn_man_btnCancelarConsorcista";
            this.btnCancelarConsorcista.UseVisualStyleBackColor = true;
            this.btnCancelarConsorcista.Enabled = false;
            this.btnCancelarConsorcista.Anchor = System.Windows.Forms.AnchorStyles.Top | System.Windows.Forms.AnchorStyles.Left;
            this.btnCancelarConsorcista.Name = "btnCancelarConsorcista";
            this.btnCancelarConsorcista.TabIndex = 13;
            this.btnCancelarConsorcista.Click += new System.EventHandler(this.btnCancelarConsorcista_Click_413BE);
            this.lbGuardado.AutoSize = true;
            this.lbGuardado.Location = new System.Drawing.Point(3, 3);
            this.lbGuardado.Name = "lbGuardado";
            this.lbGuardado.Size = new System.Drawing.Size(120, 15);
            this.lbGuardado.TabIndex = 100;
            this.lbGuardado.Tag = "lb_man_guardado";
            this.lbGuardado.Text = "Guardado";
            this.lbGuardado.Visible = false;
            this.AutoScaleDimensions = new System.Drawing.SizeF(7F, 15F);
            this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
            this.ClientSize = new System.Drawing.Size(1100, 700);
            this.Controls.Add(this.tabMaestros);
            this.Controls.Add(this.lbGuardado);
            this.MinimumSize = new System.Drawing.Size(1120, 740);
            this.Name = "frmMantenimientoConsorcios_413BE";
            this.StartPosition = System.Windows.Forms.FormStartPosition.CenterParent;
            this.Text = "Mantenimiento de consorcios";
            this.Load += new System.EventHandler(this.frmMantenimientoConsorcios_Load_413BE);
            this.FormClosing += new System.Windows.Forms.FormClosingEventHandler(this.frmMantenimientoConsorcios_FormClosing_413BE);
            ((System.ComponentModel.ISupportInitialize)(this.dgvConsorcios)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.numCantidadUnidades)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvUnidadesFuncionales)).EndInit();
            ((System.ComponentModel.ISupportInitialize)(this.dgvConsorcistas)).EndInit();
            this.tabMaestros.ResumeLayout(false);
            this.tpConsorcios.ResumeLayout(false);
            this.tpUnidadesFuncionales.ResumeLayout(false);
            this.tpConsorcistas.ResumeLayout(false);
            this.tlpConsorcios.ResumeLayout(false);
            this.pnlDetalleConsorcio.ResumeLayout(false);
            this.tlpUnidadesFuncionales.ResumeLayout(false);
            this.pnlListaUnidadesFuncionales.ResumeLayout(false);
            this.pnlFiltroConsorcioUF.ResumeLayout(false);
            this.pnlDetalleUnidadFuncional.ResumeLayout(false);
            this.tlpConsorcistas.ResumeLayout(false);
            this.pnlListaConsorcistas.ResumeLayout(false);
            this.pnlFiltroConsorcista.ResumeLayout(false);
            this.pnlDetalleConsorcista.ResumeLayout(false);
            this.ResumeLayout(false);
        }

        #endregion

        private System.Windows.Forms.Label lbGuardado;
        private System.Windows.Forms.TabControl tabMaestros;
        private System.Windows.Forms.TabPage tpConsorcios;
        private System.Windows.Forms.TabPage tpUnidadesFuncionales;
        private System.Windows.Forms.TabPage tpConsorcistas;
        private System.Windows.Forms.TableLayoutPanel tlpConsorcios;
        private System.Windows.Forms.DataGridView dgvConsorcios;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorciosColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorciosColNombre;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorciosColDireccion;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorciosColCantidadUnidades;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorciosColActivo;
        private System.Windows.Forms.Panel pnlDetalleConsorcio;
        private System.Windows.Forms.Label lblNombre;
        private System.Windows.Forms.TextBox txtNombre;
        private System.Windows.Forms.Label lblDireccion;
        private System.Windows.Forms.TextBox txtDireccion;
        private System.Windows.Forms.Label lblCantidadUnidades;
        private System.Windows.Forms.NumericUpDown numCantidadUnidades;
        private System.Windows.Forms.CheckBox chkActivo;
        private System.Windows.Forms.Button btnNuevoConsorcio;
        private System.Windows.Forms.Button btnGuardarConsorcio;
        private System.Windows.Forms.Button btnInactivarConsorcio;
        private System.Windows.Forms.Button btnReactivarConsorcio;
        private System.Windows.Forms.Button btnCancelarConsorcio;
        private System.Windows.Forms.TableLayoutPanel tlpUnidadesFuncionales;
        private System.Windows.Forms.Panel pnlListaUnidadesFuncionales;
        private System.Windows.Forms.DataGridView dgvUnidadesFuncionales;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvUnidadesFuncionalesColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvUnidadesFuncionalesColIdentificador;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvUnidadesFuncionalesColTipo;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvUnidadesFuncionalesColActiva;
        private System.Windows.Forms.Panel pnlFiltroConsorcioUF;
        private System.Windows.Forms.Label lblConsorcio;
        private System.Windows.Forms.ComboBox cboConsorcio;
        private System.Windows.Forms.Panel pnlDetalleUnidadFuncional;
        private System.Windows.Forms.Label lblIdentificador;
        private System.Windows.Forms.TextBox txtIdentificador;
        private System.Windows.Forms.Label lblTipo;
        private System.Windows.Forms.ComboBox cboTipo;
        private System.Windows.Forms.CheckBox chkActiva;
        private System.Windows.Forms.Button btnNuevoUnidadFuncional;
        private System.Windows.Forms.Button btnGuardarUnidadFuncional;
        private System.Windows.Forms.Button btnInactivarUnidadFuncional;
        private System.Windows.Forms.Button btnReactivarUnidadFuncional;
        private System.Windows.Forms.Button btnCancelarUnidadFuncional;
        private System.Windows.Forms.TableLayoutPanel tlpConsorcistas;
        private System.Windows.Forms.Panel pnlListaConsorcistas;
        private System.Windows.Forms.DataGridView dgvConsorcistas;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColId;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColDni;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColNombre;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColEmail;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColTipo;
        private System.Windows.Forms.DataGridViewTextBoxColumn dgvConsorcistasColActivo;
        private System.Windows.Forms.Panel pnlFiltroConsorcista;
        private System.Windows.Forms.Label lblConsorcioConsorcista;
        private System.Windows.Forms.ComboBox cboConsorcioConsorcista;
        private System.Windows.Forms.Label lblUnidadFuncionalConsorcista;
        private System.Windows.Forms.ComboBox cboUnidadFuncionalConsorcista;
        private System.Windows.Forms.Panel pnlDetalleConsorcista;
        private System.Windows.Forms.Label lblDni;
        private System.Windows.Forms.TextBox txtDni;
        private System.Windows.Forms.Label lblNombreConsorcista;
        private System.Windows.Forms.TextBox txtNombreConsorcista;
        private System.Windows.Forms.Label lblEmailConsorcista;
        private System.Windows.Forms.TextBox txtEmailConsorcista;
        private System.Windows.Forms.RadioButton rdoPropietario;
        private System.Windows.Forms.RadioButton rdoInquilino;
        private System.Windows.Forms.CheckBox chkActivoConsorcista;
        private System.Windows.Forms.Button btnNuevoConsorcista;
        private System.Windows.Forms.Button btnGuardarConsorcista;
        private System.Windows.Forms.Button btnInactivarConsorcista;
        private System.Windows.Forms.Button btnReactivarConsorcista;
        private System.Windows.Forms.Button btnCancelarConsorcista;
    }
}
